// Lizardmen 1.62 - re-typeset from the Warhammer Armies Project PDF.
// Imported once by extract/to_book.py; this file is the source of truth
// now, so edit it directly. Nothing regenerates it.
//
// Rules text, army design and points values are Mathias Eliasson's work.
// Only the typesetting differs here - see the colophon below.

#import "../template.typ": *

#book-meta(
  slug: "lizardmen",
  army: "Lizardmen",
  version: "1.62",
  layout: "army",
  cover: "covers/lizardmen.png",
  align: "order",
)

#show: book.with(title: "Warhammer Armies Project — Lizardmen 1.62")

#cover(
  title: "Lizardmen",
  subtitle: "Warhammer Armies Project · 1.62",
  art: "/assets/covers/lizardmen.png",
)

#colophon((
  [
    An unofficial, non-commercial re-typesetting of *Warhammer Armies Project:
    Lizardmen*, version 1.62 — written and freely distributed by Mathias
    Eliasson.
  ],
  [
    All rules text, army design and points values remain the work of their
    author. This edition changes only the typesetting; the content is
    reproduced from the freely distributed PDF.
  ],
  [
    Warhammer, Warhammer Fantasy Battle and all associated names, races and
    places are trademarks of Games Workshop Limited. This document is
    unofficial and unaffiliated, and no challenge to their status is intended.
  ],
  [Typeset with Typst. Not for sale.],
))

#outline(title: [Contents], depth: 2)

#upgrade-chapter("ARMY SPECIAL RULES", whole: true, intro: [This section of the book describes all the different units used in a Lizardmen army, along with any rules necessary to use them in your games of Warhammer. Where a model has a special rule that is explained in the _Warhammer_ rulebook, only the name of that rule is given. If a model has a special rule that is unique to it, that rule is detailed alongside its description. However, there are a number of commonly recurring ‘army special rules’ that apply to several Lizardmen units, and these are detailed here.])[
#upgrade("COLD-BLOODED", none)[
Whenever a model with this special rule takes a Leadership test, it rolls an additional dice and discards the highest result.
]

#upgrade("CHAMELEON", none)[
Models shooting at a unit with this special rule suffer a \-1 penalty To Hit.
]

#upgrade("JUNGLE POISONS", none)[
Models with this special rule have the Poisoned Attacks special rule on all their missile attacks from javelins and shortbows.
]

#upgrade("PREDATORY FIGHTER", none)[
Whenever a model with this special rule rolls a 6 To Hit in close combat, it immediately makes another Attack; roll To Hit and To Wound as normal. Attacks generated by the Predatory Fighter special rule do not generate further Attacks. This applies to all fighting models in the unit, including models making supporting attacks. In addition, a unit that contains one or more models with this special rule that attempts to restrain pursuit suffer a Leadership modifier equal to the result they won the combat against that unit by, just like a Frenzied unit.
]

#upgrade("BLOOD FRENZY", none)[
Once a model or unit with this special rule has inflicted one or more unsaved Wounds, it immediately becomes subject to Frenzy until the end of the next turn.
]
]
#lore("THE LORE OF HIGH MAGIC")[
#spell("CONTEMPLATIONS", "Lore Attribute")[If a spell from the Lore of High Magic is successfully cast, the caster can immediately choose one of the Signature Spells from one of the eight Winds of Magic in the _Warhammer_ rulebook which they can cast for the remainder of the Magic phase. That newly chosen spell will always use that spell lore's lore attribute.]

#spell("DRAIN MAGIC", "Signature Spell", cast: "7+")[_Drain Magic_ can be cast on any unit (friend or foe) and has a range of 24". If the target is a friendly unit, Drain Magic is an *augment* spell. If the target is an enemy unit, Drain Magic is a *hex* spell. In either case, all Remains in Play spells affecting the unit are immediately dispelled, and the effects of all other spells on the target unit immediately come to an end.]

#spell("APOTHEOSIS", 1, cast: "5+")[_Apotheosis_ is an *augment* spell that targets a single model within 18". The target immediately regains a single lost Wound and the Fear special rule until the start of the caster's next Magic phase.]

#spell("HAND OF GLORY", 1, cast: "5+")[_Hand of Glory_ is an *augment* spell with a range of 18". The target's Weapon Skill, Ballistic Skill, Initiative or Movement (choose one) is increased by D3 until the start of the caster's next Magic phase.]

#spell("CORUSCATING FULCRUM", 1, cast: "6+")[Remains in play. _Coruscating Fulcrum_ is an *augment* spell that is cast on the Wizard itself. While the spell is in effect, the Wizard add 12" to the range of all their spells, can draw Line of Sight in any direction and counts as having a Line of Sight value of 5.]

#spell("FORTUNE IS FICKLE", 2, cast: "6+")[_Fortune is Fickle_ is a *hex* spell with a range of 24" that targets an enemy wizard. Until the start of the caster's next Magic phase, whenever the targets roll a double when casting spells, that counts as a Miscast.]

#spell("CURSE OF ARROW ATTRACTION", 2, cast: "7+")[_Curse of Arrow Attraction_ is a *hex* spell with a range of 24". Any missile attacks against the target may re-roll To Hit until the start of the caster's next Magic phase.]

#spell("SOUL QUENCH", 2, cast: "7+")[_Soul Quench_ is a *magic missile* with a range of 18" that causes 2D6 Strength 4 hits.]

#spell("UNYIELDING COURAGE", 3, cast: "8+")[_Unyielding Courage_ is an *augment* spell that is cast on the Wizard itself. All friendly units within 6" gain the Stubborn special rule until the start of the caster's next Magic phase.]

#spell("WALK BETWEEN WORLDS", 3, cast: "8+")[_Walk Between Worlds_ is a *conveyance* spell with a range of 18". The target gains the Ethereal special rule until the end of the phase and can immediately move up to 10" as if it were the Remaining Moves sub-phase.]

#spell("CORPOREAL UNMAKING", 3, cast: "9+")[_Corporeal Unmaking_ is a *direct damage* spell with a range of 24" that causes D6 Strength 5 Hits which Ignores Armour Saves and Regeneration.]

#spell("TEMPEST", 4, cast: "12+")[_Tempest_ is a *direct damage* spell. Place the large round template anywhere within 30" of the Wizard – it then scatters D6". All models hit by the template suffer a Strength 3 hit (models with the Fly special rule suffer a Strength 4 hit instead). Any unit under the template suffers a \-1 modifier to all To Hit rolls (both shooting and close combat) until the start of the caster's next Magic phase (shooting attacks that do not use Ballistic Skill must roll 4+ on a D6 before firing, or the shot(s) are lost).]

#spell("ARCANE UNFORGING", 4, cast: "13+")[_Arcane Unforging_ is a *direct damage* spell with a range of 24" that targets a single enemy model (even a character in a unit). The target suffers a single Wound on a dice roll greater than or equal to the model's unmodified armour save (excluding Natural Armour, models without an armour save cannot be wounded). No armour saves are permitted against a Wound caused by this spell. The owning player must then reveal to the caster all the magic items possessed by the target (if any). If the target has one or more magic items, select one of them – on the roll of 2+, that item is immediately destroyed and cannot be used for the rest of the game.]

#spell("FIERY CONVOCATION", 4, cast: "15+")[Remains in play. _Fiery Convocation_ is a *direct damage* spell with a range of 24". Every model in the target unit takes a Strength 3 hit with the Flaming Attacks special rule. At the end of every subsequent Magic phase, every model in the target unit suffers another hit with the Flaming Attacks special rule, with the Strength of each Hit increasing by 1 every time.]
]
#lore("THE LORE OF GEOMANCY")[
#spell("EARTH TREMORS", "Lore Attribute")[If one or more spells from the Lore of Geomancy is successfully cast on an enemy unit or a unit suffers one or more unsaved Wounds from it, that unit suffers \-1 to its Movement value until the start of the caster's next Magic phase. This has no effect on models with the Fly or Strider special rules.]

#spell("EARTH LINE", "Signature Spell", cast: "8+")[_Earth Line_ is a special spell. Extend a straight line from one of the battlefield corners directly to the caster. Each model (friend and foe) in the way (determined using the line template) must pass a Toughness test or suffer a Wound with the Ignores Armour Saves special rule.]

#spell("PART THE WATERS", 1, cast: "5+")[_Part the Waters_ is a special type of spell. Choose any water or marshland within 24". Treat that terrain piece as open ground until the start of the caster's next Magic phase. Any unit at least partially within it when the spell is cast or ends suffer 2D6 Strength 4 Hits (except models with the Aquatic special rule).]

#spell("EMPOWERED OBSINITE", 1, cast: "8+")[_Empowered Obsinite_ is an *augment* spell with a range of 18". The target unit gains the Armour Piercing (2) special rule until the start of the caster's next Magic phase.]

#spell("TECTONIC SHIFT", 1, cast: "8+")[_Tectonic Shift_ is a special type of spell. Choose one piece of terrain within 24". You may move the target up to 2D3" in any direction while still retaining its original facing, stopping within 1" of any other terrain. Unless it is in combat, any unit in that terrain piece is moved with it, stopping within 1" of other units. In addition, the unit is subject to Earth Tremors.]

#spell("EARTHEN RAMPARTS", 2, cast: "9+")[Remains in play. _Earthen Ramparts_ is an *augment* spell with a range of 18". While the spell is in effect, the target counts as being behind a wall (a defended obstacle that gives hard cover and a \-1 To Hit modifier to charging models in base contact with them) on all sides. The spell is immediately dispelled if the unit moves for any reason.]

#spell("ENTOMB", 2, cast: "9+")[Remains in play. _Entomb_ is a *hex* with a range of 24" that can be cast on an unengaged unit. While the spell is in effect, the target cannot move or be damaged in any way (except by spells from the Lore of Geomancy) and is treated as impassable terrain for all purposes.]

#spell("UPROOT THE MOUNTAINS", 2, cast: "9+")[_Uproot the Mountains_ is a *summoning* spell with a range of 18" that summons a brand new hill with one level, no more than 6" in diameter. Alternatively, the caster can target an existing hill within 18" and remove it from play. Any unit on or under the hill when the spell is cast are subject to Earth Tremors.]

#spell("CAVERNOUS CREVASSE", 3, cast: "10+")[_Cavernous Crevasse_ is a *direct damage* spell. Extend a straight line, 12" in length, with its starting point anywhere within 18" of the caster. Each model in the way (determined using the line template) must roll a D6 per Wound on their profile – for each roll of a 4+ they suffer a Wound which Ignores Armour Saves and Regeneration.]

#spell("SEISMIC UPHEAVAL", 3, cast: "10+")[_Seismic Upheaval_ is a *hex* with a range of 24". All models in the unit must take a Dangerous Terrain test and suffer a \-1 To Hit penalty in close combat and with missile weapons until the start of the caster's next turn until the start of the caster's next Magic phase.]

#spell("TELEPATHIC SUMMONS", 3, cast: "10+")[_Telepathic Summons_ is a *conveyance* spell that targets a friendly unit within 24". The target is immediately picked up and may be moved to any position on the battlefield within 12" of the caster, just like a summoning spell.]

#spell("ASSAULT OF STONE", 4, cast: "12+")[_Assault of Stone_ is a *direct damage* spell. Place the small round template anywhere within 24" of the Wizard – it then scatters D6". All models under the template suffer a Strength 5 hit.]

#spell("RUINATION OF CITIES", 4, cast: "13+")[_Ruination of Cities_ is a *direct damage* spell with a range of 18". The target unit suffers 2D6 Strength 5 hits. A unit that suffers any wounds from this spell will have all its movement halved (rounding up) in its next Movement phase. Units inside a building take 3D6 Strength 5 hits.]

#spell("THE GREAT LEVELLER", 4, cast: "15+")[_The Great Leveller_ is a special type of spell that targets all units (friend and foe, including the caster and their unit) within 12", even if they are engaged in close combat. All target units suffer 3D6 Strength 5 Hits.]
]
#upgrade-chapter("BLESSED SPAWNINGS", intro: [*Characters and units that can take Blessed Spawnings are detailed in the army list. The cost below only applies to characters. Lords may take up to 3 Blessed Spawnings. Heroes, Core and Special units may take up to 2 Sacred Spawnings. Core units that take more than one Blessed Spawning count as Special units, and Special units counts as Rare units.*])[
*A unit that has one or more Blessed Spawnings may only be joined by characters (excepting Slann Mage Priests) that have the same Blessed Spawnings. Characters with one or more Blessed Spawnings may join any other units as normal.*

#upgrade("BLESSED MARK OF THE OLD ONES", 10)[One per army, Characters only (not including Special Characters). The character may re-roll a total of 3 dice to either To Hit, To Wound, Armour saves or Ward saves during the game. This Blessed Spawning does not prevent the character from joining any other Blessed Spawning.]

#upgrade("BLESSED SPAWNING OF CHOTEC", 10)[Models with this Blessed Spawning re-roll failed Charge and Pursuit distances.]

#upgrade("BLESSED SPAWNING OF TEPOK", 10)[Models with this Blessed Spawning have the Magic Resistance (1) special rule.]

#upgrade("BLESSED SPAWNING OF SOTEK", 10)[Models with this Blessed Spawning have the Devastating Charge special rule.]

#upgrade("BLESSED SPAWNING OF ITZL", 5, only: "Mounted models")[Models with this Blessed Spawning re-roll failed Stupidity or Berserk Rage tests.]

#upgrade("BLESSED SPAWNING OF QUETZL", 5)[Models with this Blessed Spawning can never have their armour save reduced to less than 6+.]

#upgrade("BLESSED SPAWNING OF HUANCHI", 5, only: "Models on foot")[Models with this Blessed Spawning have the Ambushers and Forest Strider special rules.]

#upgrade("BLESSED SPAWNING OF TLAZCOTL", 5)[Models with this Blessed Spawning have the Immunity (Psychology) special rule.]

#upgrade("BLESSED SPAWNING OF TZUNKI", 5, only: "Models on foot")[Models with this Blessed Spawning have the Aquatic special rule and +2 Initiative.]
]

#upgrade-chapter("DISCIPLINES OF THE OLD ONES", intro: [*A Slann Mage-Priest can purchase Disciplines of the Old Ones as detailed in the Lizardmen Army List. Each Discipline of the Old Ones can only be taken once in each army.*])[
#upgrade("THE FOCUSED RUMINATION", 30)[Once per Magic phase, the Slann may add an additional 'free' Power dice to the casting attempt. This can cause Ultimate Power as normal, and can cause the Mage-Priest to roll more dice than normally allowed.]

#upgrade("FOCUS OF MYSTERY", 30)[The Slann Mage-Priest has the Loremaster (Lore of High Magic) special rule. This discipline cannot be combined with the Wandering Deliberations discipline.]

#upgrade("HARMONIC CONVERGENCE", 30)[The Slann Mage-Priest gains a +1 bonus to channel power and dispel dice.]

#upgrade("TRANSCENDENT HEALING", 30)[If this model is alive at the end of any friendly Magic phase, roll a number of D6 equal to the difference between the Slann Mage-Priest's starting number of Wounds and its current number of Wounds. For each roll of a 6, the Slann Mage-Priest immediately recovers a single Wound lost earlier in the battle.]

#upgrade("BECALMING COGITATION", 25)[The Slann Mage-Priest re-rolls its first failed dispel attempt in each Magic phase.]

#upgrade("SOUL OF STONE", 25)[When rolling on the Miscast table, the Slann Mage- Priest can choose to subtract 1 from the result (to a minimum of 2) or add 1 to the result (to a maximum of 12), instead of accepting the original result.]

#upgrade("THE HARROWING SCRUTINY", 20)[The Slann Mage-Priest has the Terror special rule.]

#upgrade("HIGHER STATE OF CONSCIOUSNESS", 20)[The Slann Mage-Priest has the Ethereal special rule, but cannot join units.]

#upgrade("RESERVOIR OF ELDRITCH ENERGY", 20)[At the end of the opponent's Magic phase, the Slann Mage-Priest can store a single unused dispel dice remaining in your pool. At the beginning of your next Magic phase, roll a D6; on a 2+ you can add that dice to your power pool. On the roll of a 1, that bonus dice is lost. If the Slann is slain before their next Magic phase, the bonus dice is lost.]

#upgrade("UNFATHOMABLE PRESENCE", 20)[Roll a D3 at the start of each enemy Magic phase; the Slann Mage-Priest has the Magic Resistance (\*) special rule until the end of that phase, where the result of 1 gives Magic Resistance (1), a result of 2 gives Magic Resistance (2) and a result of 3 gives Magic Resistance (3).]

#upgrade("WANDERING DELIBERATIONS", 20)[The Slann Mage-Priest may choose their spells from two lores of Magic rather than one. This discipline cannot be combined with the Focus of Mystery discipline.]

#upgrade("VAST INTELLECT", 10)[The Slann Mage-Priest can choose one additional spell.]
]

#magic-item-chapter(intro: [*This section contains the rules for some of the most iconic and powerful magical artefacts used by the Nipponese. These may be used in addition to the magic items found in the Warhammer rulebook.*])

#magic-item-section("weapon", first: true)[
#magic-weapon("SCIMITAR OF THE SUN RESPLENDENT", 45)[This weapon gives the wielder +2 Attacks and the Hatred special rule.]

#magic-weapon("BLADE OF REALITIES", 40)[No armour or Ward saves can be taken against Wounds caused by this weapon.]

#magic-weapon("BLADE OF REVERED TZUNKI", 35)[This weapon gives the wielder +1 Strength and the Ignores Armour Saves special rule.]

#magic-weapon("STEGADON WAR-SPEAR", 35)[Skink Chief on Stegadon only. Light lance. This weapon gives the bearer's mount the Impact Hits (2D6+1) special rule.]

#magic-weapon("THE LASH OF ITZAOTYL", 30)[This weapon gives the wielder the Always Strikes First special rule. In addition, any Monster successfully Hit by this weapon one or more times in a single round must pass a Leadership test. If failed, it cannot Attack this close combat phase.]

#magic-weapon("SWORD OF THE HORNET", 25)[This weapon allows the wielder to re-roll 1's To Hit, and enemies must re-roll 6's To Hit against them.]

#magic-weapon("DAGGER OF SOTEK", 15)[Skink Only. This weapon gives the wielder the Killing Blow special rule. In addition, all models from _Warhammer: Skaven_ treat the model as having the Fear special rule.]

#magic-weapon("BURNING BLADE OF CHOTEC", 15)[This weapon gives the wielder the Armour Piercing (2) and Flaming Attacks special rules.]



#magic-weapon("CLOTH OF CHOTEC", 15)[Sling. All shots from this weapon have +1 Strength.]

#magic-weapon("STAFF OF THE LOST SUN", 15)[Skink Priest or Skink High Priest only. This weapon uses the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("18\"", "5", "Multiple Shots (3)"))]

#magic-weapon("STAFF OF SOTEK", 10)[Skink Priest or Skink High Priest only. This weapon has the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("12\"", "6", "Multiple Wounds (D3), Poisoned Attacks"))]
]

#magic-item-section("armour")[
#magic-armour("SACRED STEGADON HELM OF ITZA", 40)[This armour gives the wearer a 6+ armour save. In addition, they gain +1 Toughness and the Impact Hits (D3) special rule.]

#magic-armour("HIDE OF THE COLD ONES", 40)[Oldblood or Scar-veteran on foot only. The wearer of this armour gains +1 Toughness as well as the Fear, Natural Armour (5+) and Stupidity special rules.]

#magic-armour("THE MAIMING SHIELD", 20)[Shield. This armour gives the bearer +1 Attack and the Magical Attacks special rule.]

#magic-armour("SHIELD OF THE MIRRORED POOL", 20)[Shield. Any magic missile that strikes the bearer this of armour or any unit they are with is reflected on the roll of 2+ on a D6. If the spell is reflected, the results of the magic missile are resolved against the caster of the spell and any unit they are with.]

#magic-armour("CORONAL SHIELD", 25)[Shield. All enemy models attempting to strike the bearer of this armour suffer \-1 To Hit in close combat.]
]

#magic-item-section("talisman")[
#talisman("DIVINE PLAQUE OF PROTECTION", 30)[Slann Mage-Priest only. This talisman gives the wearer and any unit they are with the Ward Save (5+) special rule against missile attacks.]

#talisman("AURA OF QUETZL", 30)[This talisman gives the wearer the Ward Save (4+) special rule against attacks with Strength 5 or more.]

#talisman("GLYPH NECKLACE", 20)[All close combat attacks directed against the bearer of this talisman suffer \-1 To Hit.]

#talisman("AMULET OF ITZL", 20)[One use only. This talisman automatically ignores the first unsaved Wound suffered.]

#talisman("ZOETIC DIAL", 15)[The bearer of this item may re-roll 1's when taking armour saves.]

#talisman("INCANDESCENT RECTRICES", 10)[One use only. If this model is slain, roll a D6. On a 3+, the model is not slain and remains with 1 Wound.]
]

#magic-item-section("arcane")[
#arcane-item("CRYSTALLINE SKULL", 60)[Each time the bearer of this item successfully casts a spell, they may add +1 Power Dice to the pool. In addition, once per battle the bearer may choose to destroy this item at the end of any of your Magic phases. If they do so, pick one enemy unit within 12". Roll a number of dice equal to the number of Power dice in the pool. For each roll of a 3+, that unit suffer a Wound that Ignores Armour Saves.]

#arcane-item("CUPPED HANDS OF THE OLD ONES", 45)[Slann Mage-Priest only. One use only. If the bearer of this item miscasts, roll a D6. On a roll of 1 the bearer suffers the results of the miscast as normal. On 2+ the miscast is ignored. In addition, any enemy Wizards within line of sight of the Slann Mage-Priest will count as having rolled a 7 on the Miscast table.]

#arcane-item("PLAQUE OF DOMINION", 35)[Bound spell (power level 5). This item contains a *hex* spell that targets all enemy Wizards within 18". The targets of this spell have the Stupidity special rule until the start of the caster's next Magic phase.]

#arcane-item("ROD OF THE STORM", 35)[Bound Spell, Power Level 7. This item contains the _Urannon's Thunderbolt_ spell from the Lore of Heavens.]

#arcane-item("THE TETRAGON OF TECTONIC DISPLACEMENT", 35)[Bound Spell (Power level 6). The Tetragon of Tectonic Displacement contains the _Tectonic Shift_ spell from the Lore of Geomancy.]

#arcane-item("CUBE OF DARKNESS", 30)[One use only. When an enemy spell has been cast, a Wizard with this item can use it instead of attempting to dispel the spell using dispel dice. If he does so, roll a D6; on the roll of a 2+ the spell is automatically dispelled – otherwise the spell is resolved as normal. In either case, roll a separate D6 for every Remains in Play spell currently in effect; on a 2+ that spell automatically ends.]

#arcane-item("PLAQUE OF XOLOC", 30)[Once use only. This item may be used before attempting to cast any spell with a casting value of 10 maximum. Once used, the spell is cast automatically without using any Power dice. It may be dispelled as normal on its minimum casting value.]

#arcane-item("DIADEM OF POWER", 20)[This item allows you to save up to two unused Power dice at the end of your Magic phase and add them to your side's Dispel dice pool in the next enemy Magic phase.]

#arcane-item("PLAQUE OF TEPEE", 15)[Every time an enemy spell targets the wearer or their unit, roll a D6. On a 5+, the spell is dispelled and has no effect. If the roll is failed, you may attempt to dispel the spell as normal.]

#arcane-item("PLAQUE OF TEPOK", 10)[Slann Mage-Priest only. The model bearing this item can choose an additional spell from another Lore of Magic than the one they have chosen.]

#arcane-item("COATL FAMILIAR", 5)[Once use only. This item can be used at the start of any of your Magic phases. When used, the bearer may attempt to cast any one spell from any Lore of Magic normally available to them.]
]

#magic-item-section("enchanted")[
#enchanted-item("PRISM OF AMYNTOK", 35)[Slann only. Bound spell, power level 7. This item contains a *direct damage* spell. Extend a straight line, 12" in length, directly away from the caster. Each model in the way (determined using the line template) suffer a Strength 6 Hit with the Flaming Attacks special rule. This has a +1 bonus To Wound against Daemons, Undead and Vampires.]

#enchanted-item("THE CLOAK OF FEATHERS", 30)[Skink character on foot only. This item gives the wearer the Fly (10) and Magic Resistance (1) special rules.]

#enchanted-item("THE EGG OF QUANGO", 30)[One use only. This item can be used at the start of any Close Combat phase. Nominate one enemy unit in base contact with the bearer or his unit, roll a D6 and consult the table below to find out what happens. Any Wounds inflicted count towards combat results.

#chart((("D6", "Result"), ("1", "The enemy unit immediately suffers D6
Strength 3 hits."), ("2-3", "The enemy unit immediately suffers D6
Strength 4 hits."), ("4-6", "The enemy unit immediately suffers 2D6
Strength 5 hits.")))]

#enchanted-item("THE HORN OF KYGOR", 30)[One use only. The bearer of this item can sound it at the start of any of his Movement phases. If they do so, all friendly monsters, monster mounts, monstrous beasts, monstrous cavalry mounts, cavalry mounts, chariot beasts and war beasts within 12" of the bearer have the Frenzy special rule until the start of their next Movement phase.]

#enchanted-item("GLEAMING PENDANT OF CHOTEC", 30)[One use only. This item may be used at the start of any close combat phase. For the remainder of the phase, all enemy units in base contact with the wearer or the unit it is with gain the Always Strikes Last special rule.]

#enchanted-item("STAR TABLET", 30)[Infantry only. The bearer of this item and any unit they join gains the Scouts special rule.]

#enchanted-item("BLOOD STATUETTE OF SPITE", 25)[One use only. Bound Spell, Power Level 5. This item contains a *direct damage* spell with a range of 18" that targets one enemy model, even in a unit. The target model must pass a Toughness test or suffer a Wound which Ignores Armour Saves. If the model takes a Wound from this spell, it must immediately take another Toughness test, losing another Wound if it fails again. This continues until either the model passes a Toughness test or is slain.]

#enchanted-item("CURSE-CHARM OF TEPOK", 20)[One use only. When an enemy Wizard rolls on the Miscast table, the bearer of this item may force them to re-roll the result.]

#enchanted-item("THRONE OF THE LOST GODS", 20)[Slann Mage-Priest only. The model gains +1 Wound and the Fly (8) special rule.]

#enchanted-item("CHARM OF THE JAGUAR WARRIOR", 15)[Saurus on foot only. This item gives the bearer Movement 8 and the Scouts special rule.]

#enchanted-item("WAR DRUM OF XAHUTEC", 15)[The bearer of this item and any unit they are with do not need to pass a Leadership test in order to march, regardless of the proximity of enemy units. In addition, any friendly unit attempting to Rally within 12" gains +1 Leadership.]

#enchanted-item("BANE HEAD", 10)[The bearer of this item gains the Multiple Wounds (2) special rule against one enemy model, nominated at the start of the battle.]

#enchanted-item("CARNOSAUR PENDANT", 10)[Saurus Oldblood or Scar-Veteran. The bearer of this item gains the Blood Frenzy special rule.]

#enchanted-item("PLAQUE OF FATE", 10)[The bearer of this item may re-roll one roll To Hit, To Wound or when taking armour or Ward saves per turn.]

#enchanted-item("RELOCATION ORB", 10)[Slann only. One use only. If the bearer of this item has suffered any unsaved Wounds at the end of any phase, they may be moved anywhere within 12" just like a summoning spell, even if they are in combat.

#runin[SOTEK]'#runin[S GAZE 10 points] Skink only. This item gives the wearer the Fear special rule]

#enchanted-item("VENOM OF THE FIREFLY FROG", 10)[This item gives the bearer the Poisoned Attacks special rule. If the bearer already has Poisoned Attacks, they may re-roll failed rolls To Wound.]

#enchanted-item("DRAGONFLY OF QUICKSILVER", 5)[If both players have models with the Scouts special rule, the Lizardmen player adds +1 to their dice roll when rolling to see who deploys their Scouts first.]
]

#magic-item-section("standard")[
#magic-standard("TOTEM OF PROPHECY", 40)[All enemy units with Line of Sight to this standard suffer a \-1 penalty to their Leadership. This standard has no effect on models with Immunity (Psychology).]

#magic-standard("SUN STANDARD OF CHOTEC", 35)[All missile attacks targeted at the unit carrying this standard from within 12" suffer \-2 To Hit, or \-1 To Hit if fired from over 12" away.]

#magic-standard("HUANCHI'S BLESSED TOTEM", 35)[Bound Spell, Power Level 6. This standard contains a *conveyance* spell that may be cast on the unit carrying it. The unit may immediately make a move directly forward using the Random Movement (2D6) special rule.]

#magic-standard("SKAVENPELT BANNER", 30)[The unit carrying this standard gains the Frenzy and Hatred (Skaven) special rules. However, all models from _Warhammer: Skaven_ gain the Hatred special rule against the unit carrying the banner.]

#magic-standard("THE JAGUAR STANDARD", 25)[The unit carrying this standard adds D3" to their charge or pursue distance.]

#magic-standard("SIGN OF SOTEK", 20)[Skinks only. The unit carrying this standard may re-roll failed rolls To Wound on any turn it charges.]
]
= LORDS

#unit("SLANN MAGE-PRIEST",
  first: true,
  profiles: (
    (name: "Slann Mage-Priest", m: 4, ws: 1, bs: 3, s: 3, t: 4, w: 5, i: 1, a: 0, ld: 9, points: 340),
    (name: "Skink Attendant", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: "-", points: ""),
  ),
  troop-type: "Monstrous Infantry (Character, Lizardman, Slann)",
  base-size: "50x50, 60x60 or 75x75",
  equipment: "Hand weapon",
  magic: "A Slann Mage-Priest is a Level 4 Wizard which can use spells from any of the eight Winds of Magic, High",
  magic-body: [
Magic or Geomancy.
  ],
  options: [
- One Slann Mage-Priest may carry the Battle Standard +25 points
- May take Magic Items and/or Disciplines of the Old Ones up to a total of 100 points
  ],
  special-rules: "Cold-Blooded",
  special-rules-body: (
    rule("Arcane Might")[The model gains +1 to cast and dispel.],
    rule("Mage-Priest Palanquin")[The Palanquin gives the Slann Mage-Priest a Ward save (4+) and the Strider special rule. Additionally, while they have the troop type Monstrous Infantry, they are never considered to be ‘models on foot' for the purposes of spells, magic items and special rules.],
    rule("Telepathic Confabulation")[At the start of each friendly Magic phase, before dice are rolled to determine the strength of the Winds of Magic, you may pick two friendly Wizards with this special rule anywhere on the battlefield and they may exchange a single spell with each other. In subsequent turns, a different pairing of Wizards with this special rule may be chosen.],
  ),
  upgrades: (
    rule("Battle Standard")[The Battle Standard Bearer can have a magic banner with no points limit. However, a Slann carrying a magic standard can only take other magic items and/or Disciplines of the Old Ones up to a total of 50 points.],
  ),
  order: ("troop-type", "base-size", "equipment", "magic", "options", "special-rules", "upgrades"),
)

#unit("SAURUS OLDBLOOD",
  profiles: (
    (name: "Saurus Oldblood", m: 4, ws: 6, bs: 0, s: 5, t: 5, w: 3, i: 3, a: 5, ld: 8, points: 150),
  ),
  troop-type: "Infantry (Character, Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Hand weapon",
  options: [
- May choose one of the following:
  - Additional hand weapon +3 points
  - Spear +3 points
  - Light lance +5 points
  - Great weapon +10 points
  - Polearm +10 points
- May take a shield +3 points
- May take light armour +3 points
- May be mounted on one of the following
  - Cold One +30 points
  - Horned One +36 points
  - Aggradon +75 points
  - Carnosaur +175 points
- May take Blessed Spawnings and/or Magic Items up to a total of 100 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (4+)",
  order: ("troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("SKINK HIGH CHIEF",
  profiles: (
    (name: "Skink High Chief", m: 6, ws: 5, bs: 6, s: 4, t: 3, w: 3, i: 7, a: 4, ld: 7, points: 70),
  ),
  troop-type: "Infantry (Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon",
  options: [
- May choose one of the following:
  - Additional hand weapon +3 points
  - Spear +3 points
  - Light lance +4 points
- May choose one of the following:
  - Sling +4 points
  - Blowpipe +4 points
  - Javelin +6 points
  - Shortbow +6 points
- May take a shield +3 points
- May take light armour +3 points
- May be mounted on one of the following
  - Raptadon +30 points
  - Horned One +36 points
  - Terradon +42 points
  - Ripperdactyl +48 points
  - Stegadon (replacing one of the crew) +215 points
- May take Blessed Spawnings and/or Magic Items up to a total of 100 points
  ],
  special-rules: "Aquatic, Cold-blooded, Jungle Poisons, Natural Armour (6+)",
  order: ("troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("SKINK HIGH PRIEST",
  profiles: (
    (name: "Skink High Priest", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 3, i: 4, a: 1, ld: 6, points: 160),
  ),
  troop-type: "Infantry (Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon",
  magic: "A Skink High Priest is a Level 3 Wizard which can use spells from the Lore of Fire, Light, Heavens, Life or Beasts.",
  options: [
- May be mounted on one of the following:
  - Terradon +42 points
  - Troglodon (replacing the Skink Oracle) +150 points
  - Stegadon with an Engine of the Gods (replacing one of the crew) +265 points
  - Coatl +270 points
- May take Blessed Spawnings and/or Magic Items up to a total of 100 points
  ],
  special-rules: "Aquatic, Cold-blooded, Natural Armour (6+)",
  special-rules-body: (
    rule("Arcane Vassal")[A Slann Mage-Priest can choose to cast any magical missile or direct damage spell through a model with this special rule within 24". If they do so, measure the spell's range from the Arcane Vassal and use that model's forward arc and line of sight for the purposes of casting the spell. If using an Arcane Vassal, a Slann Mage-Priest can cast magic missiles, even if their own unit is engaged in close combat (provided that the Arcane Vassal's is not). If a spell cast through an Arcane Vassal is miscast, the result of the miscast is applied to the Slann Mage-Priest, but the Arcane Vassal suffers a Strength 3 hit.],
  ),
  order: ("troop-type", "base-size", "equipment", "magic", "options", "special-rules"),
)

= HEROES

#unit("SAURUS SCAR-VETERAN",
  first: true,
  profiles: (
    (name: "Saurus Scar-Veteran", m: 4, ws: 5, bs: 0, s: 5, t: 5, w: 2, i: 3, a: 4, ld: 8, points: 100),
  ),
  troop-type: "Infantry (Character, Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Hand weapon",
  options: [
- One Saurus Scar-Veteran may carry the Battle Standard +25 points
- May choose one of the following:
  - Additional hand weapon +2 points
  - Spear +2 points
  - Light lance +4 points
  - Great weapon +8 points
  - Polearm +8 points
- May take a shield +2 points
- May take light armour +2 points
- May be mounted on one of the following
  - Cold One +20 points
  - Horned One +24 points
  - Aggradon +50 points
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (4+)",
  upgrades: (
    rule("Battle Standard")[The Battle Standard Bearer can have a magic banner with no points limit. However, a model carrying a magic standard can only take other magic items and/or Blessed Spawnings up to a total of 25 points.],
  ),
  order: ("troop-type", "base-size", "equipment", "options", "special-rules", "upgrades"),
)

#unit("KROXIGOR ANCIENT",
  profiles: (
    (name: "Kroxigor Ancient", m: 6, ws: 5, bs: 0, s: 6, t: 5, w: 4, i: 2, a: 5, ld: 8, points: 155),
  ),
  troop-type: "Monstrous Infantry (Character, Lizardman, Saurus)",
  base-size: "40x40 or 50x50",
  equipment: "Great weapon",
  options: [
- May take light armour +4 points
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (4+)",
  order: ("troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("SKINK CHIEF",
  profiles: (
    (name: "Skink Chief", m: 6, ws: 4, bs: 5, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 6, points: 35),
  ),
  troop-type: "Infantry (Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon",
  options: [
- One Skink Chief may carry the Battle Standard +25 points
- May choose one of the following:
  - Additional hand weapon +2 points
  - Spear +2 points
  - Light lance +3 points
- May choose one of the following:
  - Sling +4 points
  - Blowpipe +4 points
  - Javelin +6 points
  - Shortbow +6 points
- May take a shield +2 points
- May take light armour +2 points
- May be mounted on one of the following
  - Raptadon +20 points
  - Horned One +24 points
  - Terradon +28 points
  - Ripperdactyl +32 points
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Aquatic, Cold-blooded, Jungle Poisons, Natural Armour (6+)",
  upgrades: (
    rule("Battle Standard")[The Battle Standard Bearer can have a magic banner with no points limit. However, a model carrying a magic standard can only take other magic items and/or Blessed Spawnings up to a total of 25 points.],
  ),
  order: ("troop-type", "base-size", "equipment", "options", "special-rules", "upgrades"),
)

#unit("SKINK PRIEST",
  profiles: (
    (name: "Skink Priest", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 2, i: 4, a: 1, ld: 5, points: 60),
  ),
  troop-type: "Infantry (Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon",
  magic: "A Skink Priest is a Level 1 Wizard which can use spells from the Lore of Fire, Light, Heavens, Life or Beasts.",
  options: [
- May be upgraded to Level 2 Wizard +35 points
- May be mounted on a Terradon +28 points
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Aquatic, Arcane Vassal (see Skink High Priests), Cold-blooded, Natural Armour (6+)",
  order: ("troop-type", "base-size", "equipment", "magic", "options", "special-rules"),
)

#unit("CHAMELEON STALKER",
  profiles: (
    (name: "Chameleon Stalker", m: 6, ws: 4, bs: 6, s: 4, t: 3, w: 2, i: 6, a: 2, ld: 6, points: 50),
  ),
  troop-type: "Infantry (Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon, blowpipe",
  options: [
- May replace blowpipe with one of the following:
  - Sling & shield +2 points
  - Javelin & shield +4 points
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Aquatic, Chameleon, Cold-blooded, Jungle Poisons, Loner, Natural Armour (6+), Scouts, Sniper",
  order: ("troop-type", "base-size", "equipment", "options", "special-rules"),
)

= CHARACTER MOUNTS

#unit("RAPTADON",
  compact: true,
  profiles: (
    (name: "Raptadon", m: 8, ws: 3, bs: 0, s: 3, t: 3, w: 1, i: 3, a: 1, ld: 3, points: "-"),
  ),
  troop-type: "War Beast (Animal)",
  base-size: "25x50 or 30x60",
  special-rules: "Cold-Blooded",
)

#unit("COLD ONE",
  compact: true,
  profiles: (
    (name: "Cold One", m: 7, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 2, a: 2, ld: 3, points: "-"),
  ),
  troop-type: "War Beast (Animal)",
  base-size: "25x50 or 30x60",
  special-rules: "Cold-Blooded, Fear, Natural Armour (6+), Stupidity",
)

#unit("HORNED ONE",
  compact: true,
  profiles: (
    (name: "Horned One", m: 8, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 3, a: 2, ld: 3, points: "-"),
  ),
  troop-type: "War Beast (Animal)",
  base-size: "25x50 or 30x60",
  special-rules: "Cold-Blooded, Fear, Natural Armour (6+)",
)

#unit("TERRADON",
  compact: true,
  profiles: (
    (name: "Terradon", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 2, a: 1, ld: 3, points: "-"),
  ),
  troop-type: "War Beast (Animal)",
  base-size: "40x40",
  special-rules: "Fear, Fly (9), Forest Strider",
)

#unit("RIPPERDACTYL",
  compact: true,
  profiles: (
    (name: "Ripperdactyl", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 3, a: 2, ld: 3, points: "-"),
  ),
  troop-type: "War Beast (Animal)",
  base-size: "40x40",
  special-rules: "Armour Piercing (1), Fear, Fly (9), Frenzy, Killing Blow",
)

#unit("AGGRADON",
  compact: true,
  profiles: (
    (name: "Aggradon", m: 7, ws: 4, bs: 0, s: 5, t: 4, w: 3, i: 2, a: 3, ld: 3, points: "-"),
  ),
  troop-type: "Monstrous Beast (Animal)",
  base-size: "50x75",
  special-rules: "Blood Frenzy, Cold-Blooded, Natural Armour (6+)",
)

#unit("CARNOSAUR",
  profiles: (
    (name: "Carnosaur", m: 7, ws: 4, bs: 0, s: 6, t: 5, w: 5, i: 2, a: 4, ld: 5, points: "-"),
  ),
  troop-type: "Monster (Animal)",
  base-size: "50x75 or 50x100",
  options: [
- May choose any of the following:
  - *Loping Stride* +5 points
  - *Bloodroar* +15 points
  ],
  special-rules: "Blood Frenzy, Cold-Blooded, Multiple Wounds (D3), Natural Armour (5+)",
  upgrades: (
    rule("Bloodroar")[Enemy units must roll an additional D6, discarding the lowest result, for Leadership tests to resolve Terror effects caused by this beast.],
    rule("Loping Stride")[A model with this upgrade has +1 Movement.],
  ),
  order: ("troop-type", "base-size", "options", "special-rules", "upgrades"),
)

= CORE UNITS

#unit("SAURUS WARRIORS",
  first: true,
  profiles: (
    (name: "Saurus Warrior", m: 4, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 1, a: 2, ld: 8, points: 12),
  ),
  unit-size: "10+",
  troop-type: "Infantry (Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Hand weapon, shield",
  options: [
- May take spears +1.5 points/model
- May take a Blessed Spawning +1 point/model
- May upgrade one Saurus Warrior to a Leader +5 points
- May upgrade one Saurus Warrior to a Musician +5 points
- May upgrade one Saurus Warrior to a Standard Bearer +10 points
  - May take a Magic Standard worth up 50 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (5+)",
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("SKINK COHORT",
  profiles: (
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: 3),
    (name: "Kroxigor", m: 6, ws: 3, bs: 0, s: 5, t: 4, w: 3, i: 1, a: 3, ld: 7, points: 46),
  ),
  unit-size: "20+",
  troop-type: "Infantry (Lizardman, Skink, Kroxigor)",
  base-size: "20x20 or 25x25 (Skinks), 40x40 or 50x50 (Kroxigors)",
  equipment: "Hand weapon, shield (Skinks), great weapon (Kroxigors)",
  options: [
- The Skinks may choose one of the following:
  - Spears +0.5 point/model
  - Replace shields with shortbows +2 points/model
  - Javelins +3 points/model
- May take a Blessed Spawning +1 point/model
- May upgrade one Skink to a Leader +5 points
- May upgrade one Skink to a Musician +5 points
- May upgrade one Skink to a Standard Bearer +10 points
  - May take a Magic Standard worth up 25 points
  ],
  special-rules: "Aquatic, Cold-blooded, Jungle Poisons, Natural Armour (6+) (Skinks only), Natural",
  special-rules-body: [
*Armour (5+)* (Kroxigors only), *Predatory Fighter* (Kroxigors only)

- *Spawn-kin:* Skink Cohorts may include one Kroxigor for every eight Skinks to form a combined unit. When a mixed unit deploys or reforms, these Kroxigor must be placed in the unit's second rank, displacing Skink models as necessary to the back rank. When deploying or reforming a combined unit, the width of the unit's front rank cannot be less than that of its second rank. If no more Kroxigor can fit in the unit's second rank, place the remaining Kroxigor in subsequent ranks. If the unit's front rank is ever reduced so that its width is less than the width of the second rank, a Kroxigor must immediately move to the front rank (displacing rank and file models if necessary).

Whenever you are required to work out the combined unit's frontage or ranks (and therefore supporting attacks and rank bonus) count as if the footprint of the entire mixed unit was filled with Skinks.

Unless otherwise stated, close combat attacks can only target Kroxigor within a combined unit if an enemy model is either in base contact with a Kroxigor, or if an enemy model is in base contact with a Skink who is in turn in base contact with a Kroxigor. Stomps are always resolved against the Skinks (if all the Skinks are slain, any excess hits are lost). Missile and Impact Hits against a Skink Cohort that contains one or more Kroxigor are randomised by rolling a D6; on a 1\-4, the hit is resolved against a Skink, on a 5\-6 it is resolved against a Kroxigor. Casualties are always taken from the rearmost rank of the appropriate model type.
  ],
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("SKINK SKIRMISHERS",
  profiles: (
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: 6),
  ),
  unit-size: "10+",
  troop-type: "Infantry (Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon, blowpipe",
  options: [
- May replace blowpipes with one of the following:
  - Shortbows free
  - Slings & shields +1 point/model
  - Javelins & shields +1 point/model
- May take a Blessed Spawning +1 point/model
- May upgrade one Skink to a Leader +5 points
- May upgrade one Skink to a Musician +5 points
  ],
  special-rules: "Aquatic, Cold-blooded, Jungle Poisons, Natural Armour (6+), Skirmishers",
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("RAPTADON RIDERS",
  profiles: (
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: 12),
    (name: "Raptadon", m: 8, ws: 3, bs: 0, s: 3, t: 3, w: 1, i: 3, a: 1, ld: 3, points: ""),
  ),
  unit-size: "5+",
  troop-type: "Cavalry (Lizardman, Skink)",
  mount: "Raptadon (Animal)",
  base-size: "25x50 or 30x60",
  equipment: "Hand weapon, light lance, shield",
  options: [
- May replace light lances with javelins +2 points/model
- May take a Blessed Spawning +1 point/model
- May upgrade one Raptadon Rider to a Leader +5 points
- May upgrade one Raptadon Rider to a Musician +5 points
- May upgrade one Raptadon Rider to a Standard Bearer +10 points
  - May take a Magic Standard worth up 25 points
  ],
  special-rules: "Aquatic, Cold-blooded, Fast Cavalry, Natural Armour (6+)",
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("JUNGLE SWARMS",
  compact: true,
  profiles: (
    (name: "Jungle Swarm", m: 5, ws: 3, bs: 0, s: 2, t: 2, w: 6, i: 1, a: 6, ld: 3, points: 30),
  ),
  unit-size: "2-10",
  troop-type: "Swarm (Animal)",
  base-size: "40x40",
  special-rules: "Aquatic, Cold-blooded, Poisoned Attacks.",
)

#unit("TERRAWINGS",
  compact: true,
  profiles: (
    (name: "Terrawing", m: 2, ws: 3, bs: 0, s: 3, t: 3, w: 1, i: 3, a: 1, ld: 3, points: 10),
  ),
  unit-size: "5+",
  troop-type: "War Beast (Animal)",
  base-size: "25x25 or 30x30",
  special-rules: "Cold-blooded, Fly (10), Forest Strider",
)

= SPECIAL UNITS

#unit("TEMPLE GUARD",
  first: true,
  profiles: (
    (name: "Temple Guard", m: 4, ws: 4, bs: 0, s: 4, t: 4, w: 1, i: 2, a: 2, ld: 8, points: 17),
  ),
  unit-size: "10+",
  troop-type: "Infantry (Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Polearm, light armour, shield",
  options: [
- May take a Blessed Spawning +1 point/model
- May upgrade one Temple Guard to a Leader +5 points
- May upgrade one Temple Guard to a Musician +5 points
- May upgrade one Temple Guard to a Standard Bearer +10 points
  - May take a Magic Standard worth up 50 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (5+), Stubborn",
  special-rules-body: [
- *Guardians:* When a Slann joins a unit whose front rank contains five or more models with the Guardians special rule, it must be placed in the second rank, rather than the first. If the unit's front rank is ever reduced to four or fewer models with the Guardians special rule, the Slann must immediately move to the front rank (displacing rank and file models if necessary).

A Slann who is in base contact with a model with the Guardians special rule is considered to be the same Troop Type as them for the purpose of 'Look Out Sir!', and cannot be targeted separately from the rest of the unit. When casting a direct damage or magical vortex spell that originates from the Slann's base, draw this spell from the base of the model in front of the Slann instead.

- *Sacred Duty:* Whilst they are part of a combined unit that has been joined by a model with the Mage-Priest Palanquin special rule, all Temple Guard models in the combined unit have the Immunity (Psychology) special rules.
  ],
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("COLD ONE RIDERS",
  profiles: (
    (name: "Saurus", m: 4, ws: 4, bs: 0, s: 4, t: 4, w: 1, i: 2, a: 2, ld: 8, points: 24),
    (name: "Cold One", m: 7, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 2, a: 2, ld: 3, points: ""),
  ),
  unit-size: "5+",
  troop-type: "Cavalry (Lizardman, Saurus)",
  mount: "Cold One (Animal)",
  base-size: "25x50 or 30x60",
  equipment: "Hand weapon, shield",
  options: [
- May take light lances +2 points/model
- May take a Blessed Spawning +2 points/model
- May upgrade one Cold One Rider to a Leader +5 points
- May upgrade one Cold One Rider to a Musician +5 points
- May upgrade one Cold One Rider to a Standard Bearer +10 points
  - May take a Magic Standard worth up 50 points
  ],
  special-rules: "Cold-blooded, Fear, Predatory Fighter, Natural Armour (4+), Stupidity",
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("KROXIGORS",
  profiles: (
    (name: "Kroxigor", m: 6, ws: 3, bs: 0, s: 5, t: 4, w: 3, i: 1, a: 3, ld: 7, points: 46),
  ),
  unit-size: "3+",
  troop-type: "Monstrous Infantry (Lizardman, Kroxigor)",
  base-size: "40x40 or 50x50",
  equipment: "Great weapon",
  equipment-body: (
    rule("War gauntlets")[Two hand weapons. War gauntlets have the Impact Hits (1) and Magical Attacks special rules.],
  ),
  options: [
- May replace great weapons with war gauntlets free
- May take a Blessed Spawning +3 points/model
- May upgrade one Kroxigor to a Leader +5 points
  ],
  special-rules: "Aquatic, Cold-blooded, Natural Armour (5+), Predatory Fighter",
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("CHAMELEON SKINKS",
  profiles: (
    (name: "Chameleon Skink", m: 6, ws: 2, bs: 4, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: 9),
  ),
  unit-size: "5+",
  troop-type: "Infantry (Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon, blowpipe",
  options: [
- May replace blowpipes with slings & shields +1 point/model
- May take a Blessed Spawning +1 point/model
- May upgrade one Chameleon Skink to a Leader +5 points
- May upgrade one Chameleon Skink to a Musician +5 points
  ],
  special-rules: "Aquatic, Chameleon, Cold-blooded, Jungle Poisons, Loner, Natural Armour (6+), Scouts, Skirmishers",
  order: ("unit-size", "troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("HORNED ONE RIDERS",
  profiles: (
    (name: "Great Crested Skink", m: 6, ws: 3, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 6, points: 21),
    (name: "Horned One", m: 8, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 3, a: 2, ld: 3, points: ""),
  ),
  unit-size: "5+",
  troop-type: "Cavalry (Lizardman, Skink)",
  mount: "Horned One (Animal)",
  base-size: "25x50 or 30x60",
  equipment: "Light lance, shield",
  options: [
- May take a Blessed Spawning +2 points/model
- May upgrade one Great Crested Skink to a Leader +5 points
- May upgrade one Great Crested Skink to a Musician +5 points
- May upgrade one Great Crested Skink to a Standard Bearer +10 points
  - May take a Magic Standard worth up 25 points
  ],
  special-rules: "Cold-blooded, Fast Cavalry, Fear, Natural Armour (5+)",
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("TERRADON RIDERS",
  profiles: (
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: 24),
    (name: "Terradon", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 2, a: 1, ld: 3, points: ""),
  ),
  unit-size: "3+",
  troop-type: "Cavalry (Lizardman, Skink)",
  mount: "Terradon (Animal)",
  base-size: "40x40",
  equipment: "Hand weapon, light lance",
  equipment-body: [
- *Fireleech Bolas:* Fireleech bolas have the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("8\"", "4", "Flaming Attacks, Quick to Fire"))
  ],
  options: [
- May replace light lances with one of the following:
  - Shortbows +2 points/model
  - Javelins +2 points/model
  - Fireleech bolas +3 points/model
- May take shields +2 points/model
- May take an additional Skink +5 points/model
- May take a Blessed Spawning +2 points/model
- May upgrade one Terradon Rider to a Leader +5 points
  ],
  special-rules: "Cold-blooded, Fast Cavalry, Fear, Fly (9), Forest Strider, Jungle Poisons, Natural Armour",
  special-rules-body: [
*(6+)*

- *Drop Rocks:* Once per game, during the Remaining Moves sub-phase, models with this special rule may drop rocks unless they are fleeing or have declared a charge that turn. All models in a unit must drop rocks at the same time. To drop rocks, select one unengaged enemy unit that the Terradons moved over in that turn. That target immediately suffers D3 Strength 4 hits for each Terradon in the unit, distributed as Hits from shooting.
  ],
  notes: [
- Terradon Riders with 2 Skinks have a Unit Strength of 3.
  ],
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules", "notes"),
)

#unit("RIPPERDACTYL RIDERS",
  profiles: (
    (name: "Skink Brave", m: 6, ws: 3, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 6, points: 32),
    (name: "Ripperdactyl", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 3, a: 2, ld: 3, points: ""),
  ),
  unit-size: "3+",
  troop-type: "Cavalry (Lizardman, Skink)",
  mount: "Ripperdactyl (Animal)",
  base-size: "40x40",
  equipment: "Light lance, shield",
  options: [
- May take a Blessed Spawning +2 points/model
- May upgrade one Ripperdactyl Rider to a Leader +5 points
  ],
  special-rules: "Armour Piercing (1) (Ripperdactyl only), Cold-blooded, Fast Cavalry, Fear, Fly (9), Frenzy",
  special-rules-body: [
(Ripperdactyl only)*, Killing Blow* (Ripperdactyl only)*, Natural Armour (6+)*

- *Toad Rage:* Before the game starts, but after Scouts have been deployed, a Lustrian blot toad marker can be placed for each unit of Ripperdactyl Riders in your army. A single blot toad marker can be placed on any enemy unit on the tabletop, this marker remains throughout the battle. When fighting in close combat against a unit with a blot toad marker, the Ripperdactyl's Frenzy grants it D3+1 extra Attacks, instead of just 1 (roll once for the whole unit) and the Ripperdactyls re-roll all failed To Hit rolls.
  ],
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("SALAMANDER",
  profiles: (
    (name: "Salamander", m: 6, ws: 3, bs: 3, s: 4, t: 4, w: 2, i: 4, a: 2, ld: 4, points: 60),
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "War Beast (Animal)",
  handler: "3 Skinks (Lizardman, Skink)",
  base-size: "40x40 or 50x50 (Salamander), 20x20 or 25x25 (Skink)",
  equipment: "Spear (Skinks only)",
  special-rules: "Aquatic, Cold-blooded, Fear, Mixed Unit, Natural Armour (5+) (Salamander only), Natural",
  special-rules-body: [
*Armour (6+)* (Skink Handler only)*, Skirmishers.*

- *Spout Flames:* Spout Flames shoots like a fire thrower with the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("n/a", "4", "Flaming Attacks, Slow to Fire"))

If the artillery dice result is a misfire, no shots are fired and D3 Skink handlers are removed as casualties. If all Skink handlers are removed, the Salamander is subject to Frenzy for the remainder of the game.
  ],
)

#unit("RAZORDON",
  profiles: (
    (name: "Razordon", m: 6, ws: 3, bs: 3, s: 4, t: 4, w: 2, i: 4, a: 2, ld: 4, points: 50),
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "War Beast (Animal)",
  handler: "3 Skinks (Lizardman, Skink)",
  base-size: "40x40 or 50x50 (Razordon), 20x20 or 25x25 (Skink)",
  equipment: "Spear (Skinks only)",
  special-rules: "Aquatic, Cold-blooded, Fear, Mixed Unit, Natural Armour (5+) (Razordon only), Natural",
  special-rules-body: [
*Armour (6+)* (Skink Handler only)*, Skirmishers.*

- *Shoot Barbs:* Shoot Barbs shoots like an organ gun with the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("18\"", "4", "Armour Piercing (1), Quick to Fire"))

If the artillery dice result is a misfire, no shots are fired and D3 Skink Handlers are removed as casualties. If all Skink handlers are removed, the Razordon is subject to Stupidity for the remainder of the game.
  ],
)

= RARE UNITS

#unit("AGGRADON RIDERS",
  first: true,
  profiles: (
    (name: "Saurus", m: 4, ws: 4, bs: 0, s: 4, t: 4, w: 1, i: 2, a: 2, ld: 8, points: 60),
    (name: "Aggradon", m: 7, ws: 4, bs: 0, s: 5, t: 4, w: 3, i: 2, a: 3, ld: 3, points: ""),
  ),
  unit-size: "3+",
  troop-type: "Monstrous Cavalry (Lizardman, Saurus)",
  mount: "Aggradon (Animal)",
  base-size: "50x75",
  equipment: "Hand weapon, light armour, shield",
  options: [
- May take light lances +2 points/model
- May take a Blessed Spawning +3 points/model
- May upgrade one Aggradon Rider to a Leader +5 points
- May upgrade one Aggradon Rider to a Musician +5 points
- May upgrade one Aggradon Rider to a Standard Bearer +10 points
  - May take a Magic Standard worth up 50 points
  ],
  special-rules: "Blood Frenzy (Aggradon only), Cold-blooded, Predatory Fighter, Natural Armour (4+)",
  order: ("unit-size", "troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("ANCIENT SALAMANDER",
  profiles: (
    (name: "Ancient Salamander", m: 6, ws: 3, bs: 3, s: 5, t: 4, w: 3, i: 4, a: 3, ld: 4, points: 110),
    (name: "Skink", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 1, i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "Monstrous Beast (Animal)",
  handler: "3 Skinks (Lizardman, Skink)",
  base-size: "50x75 (Ancient Salamander), 20x20 or 25x25 (Skink)",
  equipment: "Spear (Skinks only)",
  special-rules: "Aquatic, Armour Piercing (1) (Salamander only), Cold-blooded, Mixed Unit, Natural",
  special-rules-body: [
*Armour (5+)* (Salamander only)*, Natural Armour (6+)* (Skink Handler only)*, Skirmishers.*

- *Stream of Fire:* Stream of Fire is a fire thrower with the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("6\"", "5", "Flaming Attacks, Slow to Fire"))

If the artillery dice result is a misfire, no shots are fired and D3 Skink Handlers are removed as casualties. If all Skink handlers are removed, the Ancient Salamander is subject to Frenzy for the remainder of the game.
  ],
)

#unit("BASTILADON",
  profiles: (
    (name: "Bastiladon", m: 4, ws: 3, bs: 0, s: 5, t: 6, w: 5, i: 1, a: 3, ld: 6, points: 175),
    (name: "Skink", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "Monster (Animal)",
  crew: "3 Skinks (Lizardman, Skink)",
  base-size: "50x100 or 60x100",
  equipment: "Ark of Sotek (Bastiladon only), javelins (Skinks only)",
  equipment-body: [
- *Ark of Sotek:* At the end of each friendly turn, nominate a Jungle Swarm unit within 6" of each Bastiladon with an Ark of Sotek and roll a D6. On a 4+, add one base to the Jungle Swarm unit. This can take the Jungle Swarm unit beyond its starting size. If the base cannot be placed (because there is not enough room, or you don't have sufficient models), it is lost. In addition, the Ark of Sotek has a special shooting attack, with the profile and rules below:

#minitable(("Range", "Strength", "Special Rules"), ("D6\"", "2", "-"))

The Ark of Sotek can be activated in any friendly Shooting phase, even if the Bastiladon has marched, charged or is engaged in close combat. When activated, all enemy units within D6" immediately take 2D6 Strength 2 hits, distributed as for shooting.

- *Revivification Crystal:* All friendly units with the Cold-blooded special rule within 6" of one or more Bastiladons with a Revivification Crystal gains the Regeneration (6+) special rule.
- *Solar Engine:* All friendly units with the Cold-blooded special rule that are within 6" of one or more Bastiladons with a Solar Engine gain +1 Initiative. Innate bound spell (power level 3). _Beam of Chotec_ is a *magic missile* with a range of 24". If successfully cast, roll a D6 and consult the table below to determine the Strength and number of hits (as well as any other effects) caused by this spell. All hits caused by Beam of Chotec are Flaming Attacks.

#chart((("D6", "Number of Hits:"), ("1", "D3 Strength 3 hits."), ("2-3", "D6 Strength 4 hits."), ("4-5", "2D6 Strength 5 hits."), ("6", "2D6 Strength 6 hits. In addition, the target suffers a -1 penalty to their Weapon Skill and Ballistic
Skill (to a minimum of 1) until the start of the Bastiladon's next Magic phase.")))
  ],
  options: [
- May take an additional Skink +3 points
- May replace the Ark of Sotek with one of the following:
  - Revivification Crystal +10 points
  - Solar Engine +40 points
  ],
  special-rules: "Cold-blooded, Jungle Poisons, Natural Armour (2+), Stubborn",
  special-rules-body: (
    rule("Impervious Defence")[For the purposes of calculating combat result bonuses, a Bastiladon counts as having no flanks or rear.],
    rule("Thunderous Bludgeon")[Before rolling To Hit, nominate one of the Bastiladon's Attacks as the Thunderous Bludgeon (a different coloured dice works best). This Attack is resolved at Strength 10 and receives a +1 To Hit bonus against models in the creature's rear arc.],
  ),
  order: ("troop-type", "crew", "base-size", "equipment", "options", "special-rules"),
)

#unit("STEGADON",
  profiles: (
    (name: "Stegadon", m: 6, ws: 3, bs: 0, s: 5, t: 6, w: 5, i: 2, a: 4, ld: 6, points: 215),
    (name: "Skink Crew", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "Monster (Animal)",
  crew: "5 Skinks (Lizardman, Skink)",
  base-size: "50x100 or 60x100",
  equipment: "Giant Bow (Stegadon only), javelins (Skinks only)",
  equipment-body: [
- *Giant Bow:* Instead of firing another missile weapon in the Shooting phase, one of the Skink Crew may fire the giant bow. This is a bolt thrower with the following profile.

#minitable(("Range", "Strength", "Special Rules"), ("36\"", "5", "Multiple Wounds (D3), Poisoned Attacks"))

- *Giant Blowpipe:* Instead of firing another missile weapon in the Shooting phase, up to two of the Skink Crew may each fire a giant blowpipe. This is an artillery weapon with the following profile.

#minitable(("Range", "Strength", "Special Rules"), ("18\"", "2", "Multiple Shots (2D6), Poisoned Attacks"))

- *Engine of the Gods:* An Engine of the Gods confers the following special rules:
  - *Arcane Configuration:* If you have one or more Engines of the Gods on the battlefield at the start of your Magic phase, select one of the eight Lores of Battle Magic from the Warhammer rulebook. Until the start of your next Magic phase, the casting values for all spells from the selected lore are reduced by 1 (to a minimum of 3).
  - *Burning Alignment:* Innate bound spell (power level 3). _Burning Alignment_ is a *direct damage* spell that targets every enemy unit within 4D6" of the model's front arc. Each target suffers D6 Strength 4 hits with the Flaming Attacks special rule.
  - *Portent of Warding:* The model and all friendly units within 6" have a Ward save (6+).
  ],
  options: [
- May replace giant bow with one of the following:
  - Giant blowpipes free
  - Engine of the Gods +50 points
- May choose any of the following:
  - Unstoppable Stampede +10 points
  - Sharpened Horns +20 points
  - Ancient +30 points
  ],
  special-rules: "Cold-blooded, Immunity (Psychology), Impact Hits (D6+1), Jungle Poisons, Natural",
  special-rules-body: [
*Armour (6+)* (Skink Crew only)*, Natural Armour (5+)* (Stegadon only)*, Stubborn.*
  ],
  upgrades: (
    rule("Ancient")[The Stegadon gains +1 Strength and the Natural Armour (6+) special rule. However, they suffer \-1 Initiative and \-1 Attacks.],
    rule("Sharpened Horns")[The Stegadon's its Impact Hits gains the Multiple Wounds (D3) special rule.],
    rule("Unstoppable Stampede")[The Stegadon gains the Devastating Charge special rule.],
  ),
  order: ("troop-type", "crew", "base-size", "equipment", "options", "special-rules", "upgrades"),
)

#unit("ARCANADON",
  profiles: (
    (name: "Arcanadon", m: 4, ws: 2, bs: 0, s: 5, t: 6, w: 6, i: 1, a: 3, ld: 6, points: 280),
    (name: "Skink", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "Monster (Animal)",
  crew: "3 Skinks (Lizardman, Skink)",
  base-size: "50x100 or 60x100",
  equipment: "Power of the Ancients (Arcanadon only), javelins (Skinks only)",
  equipment-body: [
- *Power of the Ancients:* This is a stone thrower with the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("12-36\"", "4", "Flaming Attacks, Magical Attacks, Slow to Fire"))

If a misfire is rolled, the Arcanadon suffers D3 Wounds which Ignores Armour Saves.
  ],
  special-rules: "Cold-blooded, Immunity (Psychology), Impact Hits (D6+1), Jungle Poisons, Natural",
  special-rules-body: [
*Armour (4+), Stubborn*
  ],
)

#unit("TROGLODON",
  profiles: (
    (name: "Troglodon", m: 7, ws: 3, bs: 4, s: 5, t: 5, w: 5, i: 2, a: 3, ld: 5, points: 155),
    (name: "Oracle", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: 5, points: ""),
  ),
  troop-type: "Monster (Animal)",
  crew: "1 Oracle (Lizardman, Skink)",
  base-size: "50x100",
  equipment: "Javelin (Oracle only)",
  options: [
- May take Divining Rod +5 points
  ],
  special-rules: "Aquatic, Arcane Vassal (see Skink Priests), Cold-blooded, Jungle Poisons, Poisoned Attacks",
  special-rules-body: [
(Troglodon only)*, Predatory Fighter* (Troglodon only)*, Natural Armour (4+).*

- *Primeval Roar:* Once per battle, at the start of any friendly Close Combat phase, a Troglodon can unleash its Primeval Roar. This affects the Troglodon, and all friendly units within 12". All models in these units that have the Predatory Fighter special rule gain an additional Attack on any successful To Hit roll of a 5+ until the end of the phase.
- *Spit Venom:* A Troglodon can spit its venom as a shooting attack with the following profile:

#minitable(("Range", "Strength", "Special Rules"), ("18\"", "5", "Multiple Wounds (D3), Poisoned Attacks, Quick to Fire"))
  ],
  upgrades: (
    rule("Divining Rod")[The model channels Power and Dispel dice as if they were a Level 1 Wizard.],
  ),
  order: ("troop-type", "crew", "base-size", "equipment", "options", "special-rules", "upgrades"),
)

#unit("COATL",
  profiles: (
    (name: "Coatl", m: 5, ws: 4, bs: 0, s: 5, t: 5, w: 5, i: 2, a: 4, ld: 8, points: 270),
  ),
  troop-type: "Monster (Animal)",
  base-size: "50x100 or 100x100",
  magic: "A Coatl is a Level 2 Wizard that uses spells from the Lore of Heavens.",
  special-rules: "Cold-blooded, Fly (8), Magic Resistance (3), Natural Armour (4+).",
  special-rules-body: (
    rule("Guardian of the Sacred Places")[A Coatl has the following innate Bound Spell, Power Level 3. If cast, the Lizardmen player may reposition D3 pieces of forest terrain by D6", rolling the distance for each piece at a time.],
    rule("Magical Storm")[All missile fire directed at a Coatl suffers a \-1 penalty to hit.],
  ),
)

#unit("DREAD SAURIAN",
  profiles: (
    (name: "Dread Saurian", m: 7, ws: 4, bs: 0, s: 8, t: 7, w: 10, i: 1, a: 6, ld: 6, points: 365),
  ),
  troop-type: "Monster (Animal)",
  base-size: "100x150",
  options: [
- May choose one of the following:
  - The Shadow Rebus of Huanchi +25 points
  - Quetzl's Flawless Heartstone +35 points
  - The Blazing Configuration of Chotec +35 points
  - The Golden Shroud of Tlazcotl +35 points
  - Tepok's Crystalline Eye +50 points
  ],
  special-rules: "Cold-blooded, Immunity (Psychology), Multiple Wounds (D3), Natural Armour (3+).",
  upgrades: (
    rule("The Blazing Configuration of Chotec")[The Dread Saurian gains the Flaming Attacks special rule and causes 2D6 Strength 4 Flaming Impact Hits.],
    rule("The Golden Shroud of Tlazcotl")[All attacks targeting the Dread Saurian suffer a \-1 To Hit modifier.],
    rule("Quetzl's Flawless Heartstone")[The Dread Saurian gains the Stubborn special rule and reduces its Movement rate to 5, but increases its Toughness to 8.],
    rule("The Shadow Rebus of Huanchi")[The Dread Saurian gains the Ambushers deployment special rule.],
    rule("Tepok's Crystalline Eye")[The Dread Saurian gains a Ward save (5+) which is reduced to a Ward save (6+) against Magical Attacks.],
  ),
  order: ("troop-type", "base-size", "options", "special-rules", "upgrades"),
)

= SPECIAL CHARACTERS (LORDS)

#unit("LORD MAZDAMUNDI",
  first: true,
  subtitle: "Lord of the Solar-City, He That Rides the Horned Beast",
  profiles: (
    (name: "Lord Mazdamundi", m: "-", ws: 2, bs: 3, s: 3, t: 4, w: 5, i: 2, a: 1, ld: 9, points: 730),
    (name: "Zlaaq (Stegadon)", m: 6, ws: 3, bs: 0, s: 6, t: 6, w: 5, i: 1, a: 3, ld: 6, points: ""),
  ),
  troop-type: "Monster (Special Character, Lizardman, Slann)",
  mount: "Zlaaq (Animal)",
  base-size: "50x100 or 60x100",
  magic: "A Slann Mage-Priest is a Level 4 Wizard which can use spells from any of the eight Winds of Magic, High",
  magic-body: [
Magic or Geomancy.
  ],
  disciplines-of-the-old-ones: "Becalming Cogitation, Harmonic Convergence, Soul of Stone, Transcendent Healing",
  magic-items: (
    rule("Cobra Mace of Mazdamundi")[Magic Weapon. Attacks made with the Cobra Mace have the Always Strikes First and Poisoned Attacks special rules. At the start of every Close Combat phase, all enemy models in base contact with Lord Mazdamundi must reveal their magic items. If the wielder scores one or more hits against a model that has any magic items, roll a D6; on a 6, all of that model's magic items are immediately destroyed and cannot be used further in this game.],
    rule("The Itxi Grubs")[Arcane Item. One use only. This item can be used at the start of your Magic phase. Once used, the bearer gains +D3 Power dice that phase.],
    rule("Sunburst Standard of Hexoatl")[Magic Standard. The Sunburst Standard of Hexoatl is a Battle Standard – if your army includes Lord Mazdamundi, he must be your army's Battle Standard Bearer. This does not prevent Lord Mazdamundi from also being your army's General. In addition, once per game, at the beginning of any enemy Shooting phase, Lord Mazdamundi can release the power of the Sunburst Standard. If he does so, enemy models that target Mazdamundi, or any other friendly unit within 12", with a shooting attack, suffer a \-1 To Hit penalty. This effect lasts until the end of the turn.],
  ),
  special-rules: "Arcane Might (see Slann-Mage Priests), Cold-blooded, Impact Hits (D6+1) (Zlaaq only), Immunity (Psychology), Natural Armour (2+), Stubborn, Telepathic Confabulation (see Slann-Mage Priests), Ward Save (4+)",
  special-rules-body: (
    rule("Mage-lord of Hexoatl")[Lord Mazdamundi has the Loremaster special rule for whichever Lore of Magic he chooses to select spells from and can use one more power dice than normal when casting spells.],
  ),
)

#unit("LORD KROAK",
  subtitle: "Venerable Relic-Priest, Deliverer of Itza",
  profiles: (
    (name: "Lord Kroak", m: 4, ws: 0, bs: 0, s: 3, t: 5, w: 6, i: 0, a: 0, ld: 9, points: 490),
    (name: "Skink Attendant", m: "-", ws: 2, bs: 3, s: 3, t: "-", w: "-", i: 4, a: 1, ld: "-", points: ""),
  ),
  troop-type: "Monstrous Infantry (Special Character, Lizardman, Slann)",
  base-size: "50x50, 60x60 or 75x75",
  magic: "Lord Kroak is a Level 4 Wizard; however, he knows only one spell – The Deliverance of Itza. If this spell is",
  magic-body: [
lost, forgotten, swapped or stolen by any means, Lord Kroak will immediately remember it again and, if applicable, the Wizard that swapped or stole it will immediately forget it.

#namecost("THE DELIVERANCE OF ITZA", "")
#namecost("Level 4 Cast on 12+", "")

_The Deliverance of Itza_ is a *direct damage* spell that targets all enemy units within 12" of the caster's front arc. Each target suffers 2D6 Strength 4 hits. If a target has the Daemonic, Undead or Vampiric special rules, it suffers 3D6 hits instead. Lord Kroak can choose to extend the range of this spell to 18"; if he does so, the casting value is increased to 18+. Alternatively, Lord Kroak can choose to extend the range of this spell to 24", in which case the casting value is increased to 24+.
  ],
  magic-items: (
    rule("Ceremonial Mace of Malachite")[Magic Weapon. Magical Weapons count only as mundane weapons of their type when targeting Lord Kroak in close combat.],
    rule("Golden Death Mask")[Talisman. All shooting or close combat attacks against Lord Kroak or any unit he joins suffer a \-1 To Hit penalty.],
    rule("Amulet of Itza")[Arcane Item. The Amulet gives Lord Kroak Magic Resistance (3). In addition, the Amulet of Itza adds one dice to the Lizardmen player's Dispel dice pool each turn.],
    rule("Glyph of Potec")[Enchanted Item. Against enemy models with the Daemonic, Undead or Vampiric special rules, all hits from the Standard of the Sacred Serpent are resolved at Strength 5.],
    rule("Standard of the Sacred Serpent")[Magic Standard. All enemy units in base contact with Lord Kroak takes D6 Strength 3 hits at the start of your Shooting phase.],
  ),
  options: [
- May have a Skink Attendant +3 points
  ],
  special-rules: "Cold-blooded, Flammable, Mage-Priest Palanquin, Unbreakable",
  special-rules-body: (
    rule("Eternity Guardians")[If Lord Kroak joins a unit of Temple Guard, all models in the combined unit gain the Unbreakable special rule.],
    rule("First Generation Spawning")[Lord Kroak can cast _The Deliverance of Itza_ as many times per turn as he has sufficient power dice. If Lord Kroak miscasts, roll a D6; on 2+ he does not roll on the Miscast table but instead suffers a Strength 6 hit. On a roll of 1, Lord Kroak rolls on the Miscast table as normal. In either case, if the spell was cast through an Arcane Vassal, the Arcane Vassal also suffers a Strength 6 hit.],
    rule("The Spirit of Lord Kroak")[Lord Kroak's Wizard level can never be reduced to less than 1.],
  ),
  order: ("troop-type", "base-size", "magic", "magic-items", "options", "special-rules"),
)

#unit("KROQ-GAR",
  subtitle: "Ancient Scar-Leader, Last Defender of Xhotl",
  profiles: (
    (name: "Kroq-Gar", m: 4, ws: 6, bs: 0, s: 5, t: 5, w: 3, i: 3, a: 5, ld: 8, points: 470),
    (name: "Grymloq (Carnosaur)", m: 7, ws: 4, bs: 0, s: 6, t: 5, w: 5, i: 2, a: 5, ld: 5, points: ""),
  ),
  troop-type: "Monster (Special Character, Lizardman, Saurus)",
  mount: "Grymloq (Animal)",
  base-size: "50x50 or 50x100",
  equipment: "Light armour",
  magic-items: (
    rule("Revered Spear of Tlanxla")[Magic Weapon. Light lance. Each unsaved Wound caused by the Revered Spear of Tlanxla counts as 2 unsaved Wounds when calculating combat results.],
    rule("Hand of Gods")[Enchanted Item*.* Bound spell (power level 4). Hand of Gods contains the spell _Shem's Burning Gaze_ from the Lore of Light.],
  ),
  special-rules: "Blood Frenzy (Grymloq only), Cold-blooded, Multiple Wounds (D3) (Grymloq only), Predatory Fighter, Natural Armour (2+)",
  special-rules-body: (
    rule("Army of Kroq-Gar")[Kroq-Gar must always be the Army General. An army led by Kroq-Gar may include a single unit of Saurus Cold One Riders as a Core choice.],
    rule("Sacred Spawning of Xhotl")[Kroq-Gar has a Ward save (5+). If Kroq-Gar is wounded in close combat and does not pass his Ward save, then whoever struck the blow immediately suffers an automatic Strength 5 hit.],
    rule("Attuned to the Beast")[Kroq-Gar's Carnosaur steed does not suffer from Berserk Rage.],
  ),
)

#unit("TEHENHAUIN",
  subtitle: "Prophet of Sotek, Harbinger of the Serpent God",
  profiles: (
    (name: "Tehenhauin", m: 6, ws: 6, bs: 5, s: 4, t: 3, w: 3, i: 6, a: 3, ld: 8, points: 315),
  ),
  troop-type: "Monster (Special Character, Lizardman, Saurus)",
  base-size: "40x40 or 50x50",
  equipment: "Light armour",
  magic: "Tehenhauin is a Level 3 Wizard who uses spells from the Lore of Beasts.",
  magic-items: (
    rule("Blade of the Serpent's Tongue")[Magic Weapon. The Blade of the Serpent's Tongue grants Tehenhauin the Strength Bonus (1) special rule on any turn he charges. In addition, all attacks made by the Blade of the Serpent's Tongue have the Poisoned Attacks special rule.],
    rule("Plaque of Sotek")[Talisman. The Plaque of Sotek grants Tehenhauin and any Jungle Swarms in his unit the Regeneration (6+) special rule.],
  ),
  options: [
- May be mounted on a Stegadon with an Engine of the Gods (replacing one of the crew) +265 points
  ],
  special-rules: "Aquatic, Arcane Vassal, Cold-blooded, Hatred (Skaven), Immunity (Poisoned Attacks), Natural Armour (6+), Ward save (4+)",
  special-rules-body: (
    rule("Master of Snakes")[Tehenhauin can join Jungle Swarm units, even though characters are not normally permitted to join Swarms. Whilst Tehenhauin leads a Jungle Swarm, he gains the Unbreakable special rule and the unit's Unstable special rule is ignored.],
    rule("Prophet of Sotek")[If your army includes Tehenhauin, you may upgrade any units of Skink Cohorts, Skink Skirmishers, Raptadon Riders, Horned One Riders, Terradon Riders or Ripperdactyl Riders in your army so that the Skinks have +1 Weapon Skill, as well as the Devastating Charge, Hatred (Skaven) and Immunity (Poisoned Attacks) special rule for 2 points per model. They may not take any Sacred Spawning.],
    rule("Tide of Serpents")[In close combat Tehenhauin can make an extra D6 Attacks at Initiative 1. These extra Attacks are always resolved at Weapon Skill 2 and Strength 2 and have the Poisoned Attacks special rule.],
  ),
  order: ("troop-type", "base-size", "equipment", "magic", "magic-items", "options", "special-rules"),
)

#unit("TETTO'EKO",
  subtitle: "Astromancer of the Constellations, the Beholder",
  profiles: (
    (name: "Tetto'eko", m: 6, ws: 2, bs: 3, s: 2, t: 2, w: 3, i: 4, a: 1, ld: 6, points: 240),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Skink)",
  base-size: "40x40 or 50x50",
  magic: "Tetto'eko is a Level 3 Wizard who uses spells from the Lore of Heavens.",
  magic-items: (
    rule("The Eye of the Old Ones")[Enchanted Item. After deployment, but before Vanguard moves are made, if Tetto'eko is on the battlefield he can consult the Eye of the Old Ones. If he does so, D3 friendly units of your choice gain the Vanguard special rule.],
    rule("The Stellar Staff")[Arcane Item. Tetto'eko knows the _Comet of Casandora_ spell from the Lore of Heavens in addition to his other spells. If he successfully casts it, you may re-roll the dice at the start of each Magic phase to see if the comet arrives.],
  ),
  special-rules: "Arcane Vassal, Cold-blooded, Loremaster (Lore of Heavens), Natural Armour (6+)",
  special-rules-body: (
    rule("Herald of Cosmic Events")[Roll a D6 at the start of each friendly Magic phase. On a roll of 2\-6, Tetto'Eko's calculations are correct and the cosmic event occurs; all friendly Wizards within 12" must re-roll power dice rolls of a 1 this phase. However, on a roll of 1, the Chaos Moon has corrupted Tetto'eko's calculations and all friendly Wizards within 12" casting a spell must re-roll any of the power dice that roll a 6 this phase.],
    rule("The Palanquin of Constellations")[The Palanquin of Constellations gives Tetto'eko a Ward save (5+) and Strider special rule. Additionally, while they have the troop type Infantry, he is are never considered to be a ‘model on foot' for the purposes of spells, magic items and special rules. If Tetto'eko joins a unit Skink Cohorts whose front rank contains five or more models, he must be placed in the second rank, displacing other models if necessary. If the unit's front rank is ever reduced to four or fewer models, Tetto'eko must immediately move into the front rank (displacing models if necessary).],
  ),
  notes: [
- Tetto'eko has a Line of Sight value of 2.
  ],
)

= SPECIAL CHARACTERS (HEROES)

#unit("CHAKAX",
  first: true,
  subtitle: "The Eternity Warden, Prime Guardian of Xlanhuapec",
  profiles: (
    (name: "Chakax", m: 4, ws: 5, bs: 0, s: 5, t: 5, w: 2, i: 3, a: 4, ld: 8, points: 215),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Light armour",
  magic-items: (
    rule("The Star-stone Mace")[Magic Weapon. Great weapon. At the start of every Close Combat phase, all enemy models in base contact with Chakax must reveal their magic items, and Magical weapons and armour count as mundane versions of the same type.],
    rule("The Helm of the Prime Guardian")[Magic Armour. This armour gives the wearer a 6+ armour save. Enemy units with the Scouts special rule may not use their special deployment to set up within 20" of Chakax. In addition, if an enemy unit within 20" of Chakax contains 'hidden' models (such as Assassins, Night Goblin Fanatics etc.), their presence must be announced as soon as they come within 20" of Chakax.],
    rule("The Key to the Eternity Chamber")[Enchanted Item. When fighting in a challenge, Chakax has a Ward save (5+) and his opponent gains the Always Strikes Last special rule.],
  ),
  special-rules: "Cold-blooded, Guardians, Predatory Fighter, Natural Armour (4+), Stubborn",
  special-rules-body: (
    rule("Eternity Warden")[Chakax must always issue a challenge, and can never refuse one. When fighting in a challenge, Chakax re-rolls all failed rolls To Hit.],
    rule("Ultimate Bodyguard")[Whilst Chakax is part of a combined unit that contains both a model with the Mage- Priest Palanquin special rule and Temple Guard, all models in the combined unit gain the Unbreakable special rule.],
  ),
)

#unit("GOR-ROK",
  subtitle: "The Great White Lizard, The Scarred One",
  profiles: (
    (name: "Gor-Rok", m: 4, ws: 5, bs: 0, s: 5, t: 5, w: 2, i: 3, a: 4, ld: 8, points: 230),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  magic-items: (
    rule("The Mace of Ulumak")[Magic Weapon. The Mace allows Gor-Rok to re-roll all failed To Hit rolls. In addition, when striking with the Mace of Ulumak, Gor-Rok gains an additional Attack from his Predatory Fighter special rule on any successful To Hit roll of a 5 or 6.],
    rule("The Shield of Aeons")[Magic Armour. Shield. This shield gives Gor-Rok a 5+ save rather than a 6+. In addition, any enemy model that makes a successful charge against Gor-Rok and ends the Movement phase in base contact with him must immediately take a Dangerous Terrain test with a \-1 penalty.],
  ),
  special-rules: "Blessed Mark of the Old Ones (see Blessed Spawnings), Cold-blooded, Immunity",
  special-rules-body: [
*(Psychology), Predatory Fighter, Natural Armour (4+), Stubborn*

- *Resilient:* Any successful rolls To Wound roll against Gor-Rok must be re-rolled. In addition, Gor-Rok has the Immunity (Killing Blow) special rule.
  ],
)

#unit("LOTL-BOTL",
  profiles: (
    (name: "Lotl-Botl", m: 4, ws: 5, bs: 0, s: 5, t: 5, w: 2, i: 3, a: 4, ld: 8, points: 125),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Saurus)",
  base-size: "25x25 or 30x30",
  equipment: "Hand weapon, light armour, shield",
  options: [
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Cold-blooded, Predatory Fighter, Natural Armour (4+)",
  special-rules-body: (
    rule("Blood-Curdling Roar")[Lotl-Botl has the Fear special rule in any turn whenever he charges.],
    rule("Cold-Blooded Determination")[Any unit of Saurus Warriors joined by Lotl-Botl gains a +1 bonus to their combat resolution as long as he is in the unit.],
  ),
  order: ("troop-type", "base-size", "equipment", "options", "special-rules"),
)

#unit("NAKAI THE WANDERER",
  subtitle: "Sacred Kroxigor of the First Spawning",
  profiles: (
    (name: "Nakai", m: 6, ws: 5, bs: 0, s: 6, t: 5, w: 4, i: 3, a: 5, ld: 8, points: 305),
  ),
  troop-type: "Monstrous Infantry (Special Character, Lizardman, Kroxigor)",
  base-size: "40x40 or 50x50",
  magic-items: (
    rule("The Sacred Blade of Quetzl")[Magic Weapon. Great weapon. The Sacred Blade of Quetzl grants Nakai +1 to Hit in close combat, and enemy close combat attacks against him suffer \-1 To Hit.],
  ),
  special-rules: "Aquatic, Cold-blooded, Natural Armour (3+), Regeneration (4+), Predatory Fighter",
  special-rules-body: (
    rule("Blessed Mark of the Old Ones")[Nakai has the Blessed Mark of the Old Ones (see Sacred Spawnings). In addition, Nakai has the "Hold Your Ground!" ability. Any unit that kills Nakai in close combat may not overrun. If Nakai flees from combat, then the victorious unit may not pursue.],
    rule("Jungle Spirit")[Nakai may never join any unit. Nakai always appears using the Ambushers special rule, with the following exception; he will always appear from a forest, marshland or river terrain feature rather than the table edge if able to.],
  ),
)

#unit("TIKTAQ'TO",
  subtitle: "Master of Skies, the Eye in the Heavens",
  profiles: (
    (name: "Tiktaq'to", m: 6, ws: 4, bs: 5, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 7, points: 135),
    (name: "Zwup (Terradon)", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 2, a: 1, ld: 3, points: ""),
  ),
  troop-type: "Cavalry (Special Character, Lizardman, Skink)",
  mount: "Zwup (Animal)",
  base-size: "40x40",
  magic-items: (
    rule("The Blade of Ancient Skies")[Magic Weapon. The Blade of Ancient Skies has the Ignores Armour saves special rule. In addition, when fighting against a model with the Fly special rule, attacks made with the Blade of Ancient Skies receive a +1 bonus To Hit.],
    rule("Mask of Heavens")[Enchanted Item. All Terradons in Tiktaq'to's unit use his Weapon Skill instead of their own. In addition, enemy units suffer an additional \-1 To Hit penalty when shooting Tiktaq'to and his unit.],
  ),
  special-rules: "Ambushers, Cold-blooded, Drop Rocks (see Terradons), Fear, Fly (9), Forest Strider, Natural Armour (6+)",
  special-rules-body: (
    rule("Master of Skies")[If your army contains Tiktaq'to, one unit of Terradon Riders may deploy using the Ambushers special rule.],
  ),
)

#unit("INXI-HUINZI",
  profiles: (
    (name: "Inxi-Huinzi", m: 6, ws: 4, bs: 5, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 7, points: 80),
    (name: "Xltzhpctli (Horned One)", m: 8, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 3, a: 2, ld: 3, points: ""),
  ),
  troop-type: "Cavalry (Special Character, Lizardman, Skink)",
  mount: "Xltzhpctli (Animal)",
  base-size: "25x50 or 30x60",
  equipment: "Hand weapon, javelins, light armour, shield",
  options: [
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Cold-blooded, Fear, Jungle Poisons, Multiple Shots (3), Natural Armour (5+)",
  order: ("troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("TICHI-HUICHI",
  profiles: (
    (name: "Tichi-Huichi", m: 6, ws: 4, bs: 5, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 7, points: 70),
    (name: "Horned One", m: 8, ws: 3, bs: 0, s: 4, t: 4, w: 1, i: 3, a: 2, ld: 3, points: ""),
  ),
  troop-type: "Cavalry (Special Character, Lizardman, Skink)",
  mount: "Horned One (Animal)",
  base-size: "25x50 or 30x60",
  equipment: "Light lance, shield",
  options: [
- May take Magic Items up to a total of 50 points
  ],
  special-rules: "Blessing of Sotek, Cold-blooded, Fear, Poisoned Attacks, Natural Armour (5+)",
  special-rules-body: (
    rule("Blessed by the Old Ones")[Enemies that Break Tichi-Huichi's Raiders in close combat will automatically counts as restraining from pursuit, even if they would normally be forced to pursue.],
    rule("Tichi-Huichi's Raiders")[Tichi-Huichi must be accompanied by a unit of Horned One Riders chosen from the army list at a cost of 22 points per model. This unit has a full command and the Poisoned Attacks special rule. They may not take any Sacred Spawning. Tichi-Huichi is the unit's Leader and may never choose to leave this unit.],
  ),
  order: ("troop-type", "mount", "base-size", "equipment", "options", "special-rules"),
)

#unit("ITZI-BITZI",
  subtitle: "The Piranha Warrior",
  profiles: (
    (name: "Itzi-Bitzi", m: 6, ws: 4, bs: 5, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 6, points: 80),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Light armour, shield",
  magic-items: (
    rule("The Piranha Blade")[Magic Weapon. The wielder has the Multiple Wounds (D3) and Armour Piercing special rules (1).],
    rule("The Incantation of Xetlipocutzl")[Enchanted Item. One use only. Itzi-Bitzi can use the incantation at any time in the Lizardman turn. All enemy units within 8" must immediately take a Panic test using an additional D6, discarding the lowest result.],
  ),
  special-rules: "Aquatic, Cold-blooded, Natural Armour (6+)",
)

#unit("OXYOTL",
  subtitle: "Survivor of Pahuax, the Returned, He That Hunts Unseen",
  profiles: (
    (name: "Oxyotl", m: 6, ws: 4, bs: 6, s: 4, t: 3, w: 2, i: 6, a: 3, ld: 7, points: 90),
  ),
  troop-type: "Infantry (Special Character, Lizardman, Skink)",
  base-size: "20x20 or 25x25",
  equipment: "Hand weapon",
  magic-items: (
    rule("The Golden Blowpipe of P'Toohee")[Magic Weapon. Blowpipe. Shots from this weapon has Strength 2 and the Multiple Shots (3) special rule.],
  ),
  special-rules: "Aquatic, Chameleon, Cold-blooded, Hatred (Daemons of Chaos), Loner, Natural Armour",
  special-rules-body: [
*(6+), Scouts, Sniper*

- *Master Predator:* If Oxyotl remained stationary in his preceding Movement phase, shots made from the Golden Blowpipe of P'Toohee in the Shooting phase may re-roll failed To Wound rolls.
  ],
)

#unit("TEN-ZLATI",
  subtitle: "Oracle of Lord Kroak",
  profiles: (
    (name: "Ten-Zlati", m: 6, ws: 2, bs: 3, s: 3, t: 2, w: 2, i: 4, a: 1, ld: 6, points: 120),
    (name: "Terradon", m: 2, ws: 3, bs: 0, s: 4, t: 3, w: 2, i: 2, a: 1, ld: 3, points: ""),
  ),
  troop-type: "Cavalry (Special Character, Lizardman, Skink)",
  mount: "Terradon (Animal)",
  base-size: "40x40",
  magic: "Ten-Zlati is a Level 2 Wizard who uses spells from the Lore of the Heavens.",
  equipment: "Hand weapon",
  options: [
- May take Blessed Spawnings and/or Magic Items up to a total of 50 points
  ],
  special-rules: "Arcane Vassal, Cold-blooded, Drop Rocks, Fly (9), Forest Strider, Natural Armour (6+)",
  special-rules-body: (
    rule("Oracle of Lord Kroak")[Ten-zlati's Arcane Vassal special rule can be used anywhere on the battlefield, not just within 24".],
  ),
  order: ("troop-type", "mount", "base-size", "magic", "equipment", "options", "special-rules"),
)
