"""Turn the book manifest into per-book Typst documents and the landing page.

`extract/batch.py` decides which books passed their gates and writes
build/books.json; `patch.py` writes build/editions.json for any edition derived
from them. Everything downstream is generated from those two, so a book cannot
appear on the site without having been verified.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).parent


def lit(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


# --- alignment --------------------------------------------------------------

# Read from the rulebook rather than kept here as a second list, so the site
# follows the rules. `cue` matches the sentence introducing each list.
ALIGNMENTS = (
    ("order", "Forces of Order", "forces of order"),
    ("destruction", "Forces of Destruction", "forces of destruction"),
    ("neutral", "Non-Aligned Forces", "non-aligned"),
)

# Two armies are named in that list in a shorter or longer form than the book
# they belong to carries on its cover. Matching is otherwise exact: `Dwarfs` is
# a substring of `Chaos Dwarfs`, so anything looser would misfile an army.
ALIASES = {
    "cathay": "grandcathay",
    "zombiepiratesofthevampirecoast": "zombiepirates",
}


def army_key(name: str) -> str:
    key = re.sub(r"[^a-z]", "", name.casefold().removeprefix("the "))
    return ALIASES.get(key, key)


def read_alignments(rulebook: Path) -> dict[str, str]:
    data = json.loads(rulebook.read_text(encoding="utf-8"))
    entries = [e for c in data["chapters"] for e in c["entries"]
               if e["name"] == "ALLIANCE & ALIGNMENT"]
    if len(entries) != 1:
        raise SystemExit("emit: the rulebook has no ALLIANCE & ALIGNMENT section")

    out: dict[str, str] = {}
    slug = None
    for block in entries[0]["blocks"]:
        if block["type"] == "para":
            lowered = block["text"].casefold()
            slug = next((s for s, _, cue in ALIGNMENTS if cue in lowered), None)
        elif block["type"] == "list" and slug:
            for item in block["items"]:
                out[army_key(item["text"])] = slug
            slug = None
    return out


BASE_COLOPHON = """(
  [
    An unofficial, non-commercial re-typesetting of *Warhammer Armies Project:
    {army}*, version {version} — written and freely distributed by Mathias
    Eliasson.
  ],
  [
    All rules text, army design and points values remain the work of their
    author. This edition changes only the typesetting; the content is
    reproduced from the freely distributed PDF.
  ],
  [
    Warhammer, Warhammer Fantasy Battle and all associated names, races and
    places are trademarks of Games Workshop Limited. This document is
    unofficial and unaffiliated, and no challenge to their status is intended.
  ],
  [Typeset with Typst. Not for sale.],
)"""


def wrapper(book: dict, edition: dict | None) -> str:
    # Root-relative, because `image()` consumes it inside template.typ.
    art = f'"/assets/{book["cover"]}"' if book["cover"] else "none"
    army, version = book["army"], book["version"]
    rules = book.get("layout") == "rules"
    # The rulebook is set in one column, so it takes a wider margin to keep the
    # line length readable, and its outline runs one level deeper.
    side = ", side: 3.1cm" if rules else ""
    depth = 3 if rules else 2

    if edition is None:
        title = f"Warhammer Armies Project — {army} {version}"
        subtitle = f"Warhammer Armies Project · {version}"
        colophon = BASE_COLOPHON.format(army=army, version=version)
    else:
        # An edition's own version names the set of changes; the book's names the
        # text they were applied to, so the subtitle carries both.
        stamp = f" {edition['version']}" if edition["version"] else ""
        title = f"{army} — {edition['label']}{stamp}"
        subtitle = f"{edition['label']}{stamp} · after Warhammer Armies Project {version}"
        # These arrive from edition.toml as plain strings, so they cross into
        # Typst as literals for the same reason the book's own text does.
        body = ",\n  ".join(lit(line) for line in edition["colophon"])
        colophon = f"(\n  {body},\n)"

    return f'''// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: {lit(title)}{side})

#cover(
  title: {lit(army)},
  subtitle: {lit(subtitle)},
  art: {art},
)

#colophon({colophon})

#outline(title: [Contents], depth: {depth})

#include "content/{book["id"]}.typ"
'''


CARD = """      <li class="book"{data}>
        <a href="{id}.pdf">{thumb}</a>
        <div>
          <h2><a href="{id}.pdf">{army}</a></h2>
          <p>Version {version} · {entries} entries</p>{editions}
        </div>
      </li>"""

EDITION_LINE = """
          <p class="editions"><a href="{id}.pdf">{label}</a> · {changes}</p>"""

HEAD = """      <li class="head" data-align="{align}">
        <h2>{title}</h2><span>{count} books</span>
      </li>"""

# Re-orders and filters the army grid. The page is built grouped and in source
# order, so with this switched off it still reads correctly — which is why the
# controls are revealed here rather than being present in the markup.
SCRIPT = """
const grid = document.getElementById('armies');
const controls = document.getElementById('controls');
const cards = [...grid.querySelectorAll('.book')];
const heads = [...grid.querySelectorAll('.head')];
const alpha = [...cards].sort((a, b) => a.dataset.name.localeCompare(b.dataset.name));
let filter = 'all', sort = 'grouped';

function apply() {
  for (const card of cards) {
    card.hidden = filter !== 'all' && card.dataset.align !== filter;
    card.style.order = '';
  }
  for (const head of heads) {
    head.hidden = sort === 'alpha' || (filter !== 'all' && head.dataset.align !== filter);
  }
  if (sort === 'alpha') alpha.forEach((card, i) => { card.style.order = i + 1; });
}

for (const button of controls.querySelectorAll('button')) {
  button.addEventListener('click', () => {
    const group = button.dataset.filter ? 'filter' : 'sort';
    if (group === 'filter') filter = button.dataset.filter; else sort = button.dataset.sort;
    for (const sibling of button.parentElement.children) {
      sibling.setAttribute('aria-pressed', String(sibling === button));
    }
    apply();
  });
}
controls.hidden = false;
apply();
"""

CONTROLS = """  <div class="controls" id="controls" hidden>
    <div class="set" role="group" aria-label="Filter by alignment">
      <button data-filter="all" aria-pressed="true">All</button>
      <button data-filter="order" aria-pressed="false">Order</button>
      <button data-filter="destruction" aria-pressed="false">Destruction</button>
      <button data-filter="neutral" aria-pressed="false">Non-aligned</button>
    </div>
    <div class="set" role="group" aria-label="Order">
      <button data-sort="grouped" aria-pressed="true">Grouped</button>
      <button data-sort="alpha" aria-pressed="false">A–Z</button>
    </div>
  </div>"""


def sort_name(book: dict) -> str:
    """`The Empire` files under E, as it would on a shelf."""
    return book["army"].casefold().removeprefix("the ")


def card(book: dict, derived: dict[str, list[dict]], align: str | None) -> str:
    army = html.escape(book["army"])
    # Images are copied without re-encoding, so the extension follows the
    # source rather than being assumed.
    thumb = '<span class="nothumb"></span>'
    if book["cover"]:
        ext = Path(book["cover"]).suffix
        thumb = (f'<img src="{book["id"]}-cover{ext}" '
                 f'alt="{army} cover" loading="lazy">')
    editions = "".join(
        EDITION_LINE.format(
            id=e["id"], label=html.escape(e["edition_label"]),
            changes=f"{e['changes']} change" + ("s" if e["changes"] != 1 else ""),
        )
        for e in derived.get(book["id"], [])
    )
    data = ""
    if align:
        data = (f' data-align="{align}" '
                f'data-name="{html.escape(sort_name(book), quote=True)}"')
    return CARD.format(
        id=book["id"], army=army, thumb=thumb, editions=editions, data=data,
        version=html.escape(book["version"]), entries=book["entries"],
    )


def page(books: list[dict], derived: dict[str, list[dict]],
         align: dict[str, str], css: str) -> str:
    rules = [b for b in books if b.get("layout") == "rules"]
    armies = sorted((b for b in books if b.get("layout") != "rules"), key=sort_name)

    # Built grouped and in source order, so the page is correct before the
    # script runs; A–Z is a re-ordering of what is already here.
    rows = []
    for slug, title, _ in ALIGNMENTS:
        group = [b for b in armies if align[b["id"]] == slug]
        rows.append(HEAD.format(align=slug, title=title, count=len(group)))
        rows.extend(card(b, derived, slug) for b in group)

    # The rulebook's entries are sections of prose, not units, so they are not
    # added to a count the line below calls unit entries.
    total = sum(b["entries"] for b in armies)
    count = sum(len(v) for v in derived.values())
    note = ""
    if count:
        note = ("""
  <p class="note">
    Some books carry a second, <strong>modified</strong> edition alongside the
    original — our own amendments, made for our own table. Where one exists it is
    linked beneath the book, and every change it makes is listed in the back of
    it.
  </p>""")

    core = ""
    if rules:
        core = f"""
  <h2 class="section">The Rules</h2>
  <ul class="books core">
{chr(10).join(card(b, derived, None) for b in rules)}
  </ul>
"""

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Warhammer Armies Project — typeset editions</title>
<style>
{css}</style>
</head>
<body>
<main>
  <h1>Warhammer Armies Project</h1>
  <p class="sub">{len(armies)} army books and the core rulebook, {total:,} unit entries, re-typeset with Typst.</p>
{note}
{core}
  <h2 class="section">The Armies</h2>
{CONTROLS}
  <ul class="books" id="armies">
{chr(10).join(rows)}
  </ul>

  <hr>

  <footer>
    <p>
      These are unofficial, non-commercial re-typesettings of the
      <strong>Warhammer Armies Project</strong> army books, written and freely
      distributed by Mathias Eliasson. All rules text, army design and points
      values remain the work of their author; only the typesetting differs.
    </p>
    <p>
      Editions marked as modified are the exception: those alter the rules text
      itself. The alterations are ours, not the author's, and each book lists
      them in full.
    </p>
    <p>
      Warhammer, Warhammer Fantasy Battle and all associated names, races and
      places are trademarks of Games Workshop Limited. This site is unofficial
      and unaffiliated, and no challenge to their status is intended.
    </p>
    <p>Built from Typst sources. Not for sale.</p>
  </footer>
</main>
<script>
{SCRIPT}</script>
</body>
</html>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", type=Path, default=ROOT / "build" / "books.json")
    ap.add_argument("--editions", type=Path, default=ROOT / "build" / "editions.json")
    args = ap.parse_args()

    books = json.loads(args.manifest.read_text(encoding="utf-8"))["books"]
    for book in books:
        book["id"] = book["slug"]

    editions: dict[str, dict] = {}
    derived: dict[str, list[dict]] = {}
    if args.editions.exists():
        data = json.loads(args.editions.read_text(encoding="utf-8"))
        editions = {e["slug"]: e for e in data["editions"]}
        for record in data["books"]:
            derived.setdefault(record["base"], []).append(record)

    rulebook = next((b for b in books if b.get("layout") == "rules"), None)
    if rulebook is None:
        raise SystemExit("emit: the manifest has no rulebook to read alignments from")
    listed = read_alignments(ROOT / "build" / f"{rulebook['slug']}.json")

    align, unaligned = {}, []
    for book in books:
        if book.get("layout") == "rules":
            continue
        slug = listed.get(army_key(book["army"]))
        if slug is None:
            unaligned.append(book["army"])
        align[book["id"]] = slug
    if unaligned:
        raise SystemExit(
            f"emit: not named in the rulebook's alignment lists: "
            f"{', '.join(sorted(unaligned))}. Add an alias if the book's title "
            f"differs from the name it is listed under.")

    css = (ROOT / "site" / "style.css").read_text(encoding="utf-8")
    content = ROOT / "src" / "content"

    written, missing, render = [], [], []
    for book in books + [b for v in derived.values() for b in v]:
        if not (content / f"{book['id']}.typ").exists():
            missing.append(book["id"])
            continue
        edition = editions.get(book.get("edition"))
        (ROOT / "src" / f"{book['id']}.typ").write_text(
            wrapper(book, edition), encoding="utf-8")
        written.append(book["id"])
        # An edition shares the book's cover art, which the site already has.
        render.append({"id": book["id"],
                       "cover": "" if edition else book["cover"]})

    # Stale wrappers would still be compiled by the workflow, which walks the
    # render list, but leaving them behind makes src/ lie about what is built.
    live = set(written)
    for old in (ROOT / "src").glob("*.typ"):
        if old.stem not in live and old.name != "template.typ":
            old.unlink()
            print(f"  removed stale wrapper {old.name}")

    (ROOT / "site" / "index.html").write_text(page(books, derived, align, css),
                                              encoding="utf-8")
    (ROOT / "build" / "render.json").write_text(
        json.dumps(render, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")

    count = sum(len(v) for v in derived.values())
    print(f"wrote {len(written)} Typst wrappers into src/ "
          f"({len(books)} books, {count} derived editions)")
    print(f"wrote site/index.html and build/render.json")
    if missing:
        print(f"  NO CONTENT for: {', '.join(missing)} "
              f"(run extract/to_typst.py or patch.py for these)")
        sys.exit(1)


if __name__ == "__main__":
    main()
