"""Turn the book manifest into per-book Typst documents and the landing page.

`extract/batch.py` decides which books passed their gates and writes
build/books.json; everything downstream is generated from that, so a book cannot
appear on the site without having been verified.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).parent


def lit(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def wrapper(book: dict) -> str:
    art = f'"../assets/{book["cover"]}"' if book["cover"] else "none"
    army, version = book["army"], book["version"]
    return f'''// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: {lit(f"Warhammer Armies Project — {army} {version}")})

#cover(
  title: {lit(army)},
  subtitle: {lit(f"Warhammer Armies Project · {version}")},
  art: {art},
)

#colophon((
  [
    An unofficial, non-commercial re-typesetting of *Warhammer Armies Project:
    {army}*, version {version} — written and freely distributed by Mathias
    Eliasson.
  ],
  [
    All rules text, army design and points values remain the work of their
    author. This edition changes only the typesetting; the content is
    reproduced from the freely distributed PDF.
  ],
  [
    Warhammer, Warhammer Fantasy Battle and all associated names, races and
    places are trademarks of Games Workshop Limited. This document is
    unofficial and unaffiliated, and no challenge to their status is intended.
  ],
  [Typeset with Typst. Not for sale.],
))

#outline(title: [Contents], depth: 2)

#include "content/{book["slug"]}.typ"
'''


CARD = """    <li class="book">
      <a href="{slug}.pdf">{thumb}</a>
      <div>
        <h2><a href="{slug}.pdf">{army}</a></h2>
        <p>Version {version} · {entries} entries</p>
      </div>
    </li>"""


def page(books: list[dict], css: str) -> str:
    cards = []
    for book in books:
        army = html.escape(book["army"])
        thumb = (
            f'<img src="{book["slug"]}-cover.png" alt="{army} cover" loading="lazy">'
            if book["cover"] else '<span class="nothumb"></span>'
        )
        cards.append(CARD.format(
            slug=book["slug"], army=army, thumb=thumb,
            version=html.escape(book["version"]), entries=book["entries"],
        ))
    total = sum(b["entries"] for b in books)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Warhammer Armies Project — typeset editions</title>
<style>
{css}</style>
</head>
<body>
<main>
  <h1>Warhammer Armies Project</h1>
  <p class="sub">{len(books)} army books, {total:,} unit entries, re-typeset with Typst.</p>

  <ul class="books">
{chr(10).join(cards)}
  </ul>

  <hr>

  <footer>
    <p>
      These are unofficial, non-commercial re-typesettings of the
      <strong>Warhammer Armies Project</strong> army books, written and freely
      distributed by Mathias Eliasson. All rules text, army design and points
      values remain the work of their author; only the typesetting differs.
    </p>
    <p>
      Warhammer, Warhammer Fantasy Battle and all associated names, races and
      places are trademarks of Games Workshop Limited. This site is unofficial
      and unaffiliated, and no challenge to their status is intended.
    </p>
    <p>Built from Typst sources. Not for sale.</p>
  </footer>
</main>
</body>
</html>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", type=Path, default=ROOT / "build" / "books.json")
    args = ap.parse_args()

    books = json.loads(args.manifest.read_text(encoding="utf-8"))["books"]
    css = (ROOT / "site" / "style.css").read_text(encoding="utf-8")

    content = ROOT / "src" / "content"
    written, missing = [], []
    for book in books:
        if not (content / f"{book['slug']}.typ").exists():
            missing.append(book["slug"])
            continue
        (ROOT / "src" / f"{book['slug']}.typ").write_text(wrapper(book), encoding="utf-8")
        written.append(book["slug"])

    # Stale wrappers would still be compiled by the workflow, which walks the
    # manifest, but leaving them behind makes src/ lie about what is built.
    live = {b["slug"] for b in books}
    for old in (ROOT / "src").glob("*.typ"):
        if old.stem not in live and old.name != "template.typ":
            old.unlink()
            print(f"  removed stale wrapper {old.name}")

    (ROOT / "site" / "index.html").write_text(page(books, css), encoding="utf-8")

    print(f"wrote {len(written)} Typst wrappers into src/")
    print(f"wrote site/index.html listing {len(books)} books")
    if missing:
        print(f"  NO CONTENT for: {', '.join(missing)} "
              f"(run extract/to_typst.py for these)")
        sys.exit(1)


if __name__ == "__main__":
    main()
