"""Render extracted army-book JSON as Typst source.

Text crosses into Typst as string literals rather than markup, so nothing in
the source book can be reinterpreted as Typst syntax — no escaping table to get
wrong, and a unit called `*Ancient*` stays literal.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def lit(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def arr(items: list[str]) -> str:
    """A Typst array. Single-element arrays need the trailing comma or they are
    parsed as a parenthesised expression."""
    if not items:
        return "()"
    if len(items) == 1:
        return f"({items[0]},)"
    return "(" + ", ".join(items) + ")"


def runs_lit(runs: list[dict]) -> str:
    return arr([
        f"(emph: {lit(r['emph'])}, text: {lit(r['text'])})" for r in runs
    ])


def block_lines(block: dict) -> list[str]:
    kind = block["type"]

    if kind == "statblock":
        cols = block["columns"]
        rows = [
            arr([lit(row["name"])] + [lit(row["values"].get(c, "")) for c in cols])
            for row in block["rows"]
        ]
        label = lit(block.get("label", "Profile"))
        return [f"#statblock({label}, {arr([lit(c) for c in cols])}, {arr(rows)})"]

    if kind == "namecost":
        return [f"#namecost({lit(block['name'])}, {lit(block['cost'])})"]

    if kind == "minitable":
        cols = block["columns"]
        vals = [lit(block["row"].get(c, "")) for c in cols]
        return [f"#minitable({arr([lit(c) for c in cols])}, {arr(vals)})"]

    if kind == "field":
        return [f"#field({lit(block['label'])}, {lit(block['value'])})"]

    if kind == "para":
        style = block.get("style", "body")
        suffix = ', style: "italic"' if style == "italic" else ""
        return [f"#para({runs_lit(block['runs'])}{suffix})"]

    if kind == "list":
        entries = [
            f"(runs: {runs_lit(it['runs'])}, "
            f"sub: {arr([runs_lit(s['runs']) for s in it['sub']])})"
            for it in block["items"]
        ]
        return [f"#items({arr(entries)})"]

    return []


def chapter_lines(chapter: dict) -> list[str]:
    out: list[str] = []
    for block in chapter.get("intro", []):
        out.extend(block_lines(block))
    for entry in chapter["entries"]:
        out.append("")
        out.append(f"#heading(level: 2, {lit(entry['name'])})")
        for block in entry["blocks"]:
            out.extend(block_lines(block))
    return out


def all_blocks(chapter: dict) -> list[dict]:
    pools = [chapter.get("intro", [])] + [e["blocks"] for e in chapter["entries"]]
    return [b for pool in pools for b in pool]


def has_statblock(chapter: dict) -> bool:
    return any(b["type"] == "statblock" for b in all_blocks(chapter))


def text_length(chapter: dict) -> int:
    total = 0
    for block in all_blocks(chapter):
        kind = block["type"]
        if kind == "para":
            total += len(block["text"])
        elif kind == "field":
            total += len(block["value"])
        elif kind == "namecost":
            total += len(block["name"])
        elif kind == "list":
            total += sum(
                len(it["text"]) + sum(len(s["text"]) for s in it["sub"])
                for it in block["items"]
            )
    return total


# Below this much prose a two-column setting leaves the second column stranded
# empty, which reads as a layout fault rather than a choice.
TWO_COLUMN_MIN = 3000


def two_column(chapter: dict) -> bool:
    return not has_statblock(chapter) and text_length(chapter) >= TWO_COLUMN_MIN


def render(data: dict, template: str) -> str:
    # `include` evaluates a file in its own module scope, so the template has to
    # be imported here rather than inherited from the including document.
    lines: list[str] = [
        "// Generated by extract/to_typst.py - do not edit by hand.",
        f'#import "{template}": *',
        "",
    ]
    for chapter in data["chapters"]:
        lines.append(f"#heading(level: 1, {lit(chapter['title'])})")
        body = chapter_lines(chapter)
        if two_column(chapter):
            lines.append("#columns(2)[")
            lines.extend(body)
            lines.append("]")
        else:
            # Stat tables need the full measure, and short chapters would leave
            # the second column empty; both stay single column.
            lines.extend(body)
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("json", type=Path)
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument("--template", default="../template.typ",
                    help="template path, relative to the generated file")
    args = ap.parse_args()

    data = json.loads(args.json.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(data, args.template), encoding="utf-8")

    prose = [c["title"] for c in data["chapters"] if two_column(c)]
    print(f"wrote {args.out}")
    print(f"  two-column prose chapters: {', '.join(prose) or 'none'}")


if __name__ == "__main__":
    main()
