// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: "Daemons of Chaos — House Rules 2026.1")

#cover(
  title: "Daemons of Chaos",
  subtitle: "House Rules 2026.1 · after Warhammer Armies Project 3.0",
  art: "/assets/covers/daemons-of-chaos.png",
)

#colophon((
  "This is a MODIFIED edition. The rules text has been altered from the original in the places listed under Our Changes, and those alterations are not marked in the body. Do not take a rule here to be the author's wording without checking that chapter.",
  "The underlying work is the Warhammer Armies Project, written and freely distributed by Mathias Eliasson. All rules text, army design and points values are his; the amendments are ours alone, made for our own table, and carry no endorsement from him.",
  "Warhammer, Warhammer Fantasy Battle and all associated names, races and places are trademarks of Games Workshop Limited. This document is unofficial and unaffiliated, and no challenge to their status is intended.",
  "Typeset with Typst. Not for sale.",
))

#outline(title: [Contents], depth: 2)

#include "content/daemons-of-chaos-house.typ"
