// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: "The Game of Fantasy Battles — Proposals 2026.1", side: 3.1cm)

#cover(
  title: "The Game of Fantasy Battles",
  subtitle: "Proposals 2026.1 · after Warhammer Armies Project 3.11",
  art: "/assets/covers/rulebook.png",
)

#colophon((
  "The rules in this book are the ones we play. Nothing in the body has been altered by the proposals: they are set out in their own chapter at the back, each as a description of what it would change and why, and none of them is in force. A proposal only becomes a rule once it is agreed, and it will appear under Our Changes when it does.",
  "The underlying work is the Warhammer Armies Project, written and freely distributed by Mathias Eliasson. All rules text, army design and points values are his; the amendments and the proposals are ours alone, made for our own table, and carry no endorsement from him.",
  "Warhammer, Warhammer Fantasy Battle and all associated names, races and places are trademarks of Games Workshop Limited. This document is unofficial and unaffiliated, and no challenge to their status is intended.",
  "Typeset with Typst. Not for sale.",
))

#outline(title: [Contents], depth: 3)

#include "content/rulebook-proposal.typ"
