// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: "Warhammer Armies Project — Tomb Kings 3.1")

#cover(
  title: "Tomb Kings",
  subtitle: "Warhammer Armies Project · 3.1",
  art: "../assets/covers/tomb-kings.png",
)

#colophon((
  [
    An unofficial, non-commercial re-typesetting of *Warhammer Armies Project:
    Tomb Kings*, version 3.1 — written and freely distributed by Mathias
    Eliasson.
  ],
  [
    All rules text, army design and points values remain the work of their
    author. This edition changes only the typesetting; the content is
    reproduced from the freely distributed PDF.
  ],
  [
    Warhammer, Warhammer Fantasy Battle and all associated names, races and
    places are trademarks of Games Workshop Limited. This document is
    unofficial and unaffiliated, and no challenge to their status is intended.
  ],
  [Typeset with Typst. Not for sale.],
))

#outline(title: [Contents], depth: 2)

#include "content/tomb-kings.typ"
