// Generated by emit.py - do not edit by hand.
#import "template.typ": *

#show: book.with(title: "Tyranids 1.0 — an original army book")

#cover(
  title: "Tyranids",
  subtitle: "An original army book · for Warhammer Armies Project",
  art: none,
)

#colophon((
  [
    An original, unofficial army book written for use with the *Warhammer
    Armies Project*, Mathias Eliasson's freely distributed fan ruleset. This
    book is not his work: its rules, army design and points values are our
    own house material, version 1.0.
  ],
  [
    Warhammer, Warhammer Fantasy Battle, Warhammer 40,000 and all associated
    names, races and places are trademarks of Games Workshop Limited. This
    document is unofficial and unaffiliated, and no challenge to their status
    is intended.
  ],
  [Typeset with Typst. Not for sale.],
))

#outline(title: [Contents], depth: 2)

#include "content/tyranids.typ"
